
SET NAMES utf8;                        
  

            
UPDATE skyfire_string SET content_loc2 = 'Vous devez sélectionner un personnage ou une créature.' WHERE entry = 1;
UPDATE skyfire_string SET content_loc2 = 'Vous devez sélectionner une créature.' WHERE entry = 2;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Message Systeme]: %s|r' WHERE entry = 3;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Annonce d\'evenement]: %s|r' WHERE entry = 4;
UPDATE skyfire_string SET content_loc2 = 'Aucune aide n\'est disponible pour cette commande.' WHERE entry = 5;
UPDATE skyfire_string SET content_loc2 = 'Cette commande n\'existe pas.' WHERE entry = 6;
UPDATE skyfire_string SET content_loc2 = 'Cette sous-commande n\'existe pas.' WHERE entry = 7;
UPDATE skyfire_string SET content_loc2 = 'La commande %s possède les sous-commandes suivantes: %s' WHERE entry = 8;
UPDATE skyfire_string SET content_loc2 = 'Commandes disponibles:' WHERE entry = 9;
UPDATE skyfire_string SET content_loc2 = 'Syntaxe incorrecte.' WHERE entry = 10;
UPDATE skyfire_string SET content_loc2 = 'Votre niveau de compte est: %i' WHERE entry = 11;
UPDATE skyfire_string SET content_loc2 = 'Connexions Actives: %u (max: %u) Joueurs dans la file d\'attente: %u (max: %u)' WHERE entry = 12;
UPDATE skyfire_string SET content_loc2 = 'Serveur en-ligne depuis: %s' WHERE entry = 13;
UPDATE skyfire_string SET content_loc2 = 'Joueur sauvegarde.' WHERE entry = 14;
UPDATE skyfire_string SET content_loc2 = 'Tous les joueurs ont été sauvegardés.' WHERE entry = 15;
UPDATE skyfire_string SET content_loc2 = 'Maitres-du-jeu disponibles:' WHERE entry = 16;
UPDATE skyfire_string SET content_loc2 = 'Aucun MJ n\'est actuellement connecté.' WHERE entry = 17;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas faire cela en vol.' WHERE entry = 18;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas faire cela sur un champ de Bataille.' WHERE entry = 19;
UPDATE skyfire_string SET content_loc2 = 'La cible est en vol, vous ne pouvez pas faire cela.' WHERE entry = 20;
UPDATE skyfire_string SET content_loc2 = '%s est en vol, la commande a echoue.' WHERE entry = 21;
UPDATE skyfire_string SET content_loc2 = 'Vous n\'étés pas sur une monture, vous ne pouvez donc pas en descendre.' WHERE entry = 22;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas faire cela en combattant.' WHERE entry = 23;
UPDATE skyfire_string SET content_loc2 = 'Vous l\'avez déja utilise recemment.' WHERE entry = 24;
UPDATE skyfire_string SET content_loc2 = 'Le mot de passe n\'a pas été changé (erreur inconnue) !' WHERE entry = 25;
UPDATE skyfire_string SET content_loc2 = 'Le mot de passe a été changé.' WHERE entry = 26;
UPDATE skyfire_string SET content_loc2 = 'Le nouveau mot de passe ne correspond pas, ou l\'ancien est mauvais.' WHERE entry = 27;
UPDATE skyfire_string SET content_loc2 = 'Votre compte est maintenant bloque.' WHERE entry = 28;
UPDATE skyfire_string SET content_loc2 = 'Votre compte est maintenant debloque.' WHERE entry = 29;
UPDATE skyfire_string SET content_loc2 = ', Rang' WHERE entry = 30;
UPDATE skyfire_string SET content_loc2 = '[Connu]' WHERE entry = 31;
UPDATE skyfire_string SET content_loc2 = '[Appris]' WHERE entry = 32;
UPDATE skyfire_string SET content_loc2 = '[Passive]' WHERE entry = 33;
UPDATE skyfire_string SET content_loc2 = '[Talent]' WHERE entry = 34;
UPDATE skyfire_string SET content_loc2 = '[Actif]' WHERE entry = 35;
UPDATE skyfire_string SET content_loc2 = '[Termine]' WHERE entry = 36;
UPDATE skyfire_string SET content_loc2 = '(Hors ligne)' WHERE entry = 37;
UPDATE skyfire_string SET content_loc2 = 'Actif' WHERE entry = 38;
UPDATE skyfire_string SET content_loc2 = 'Ferme' WHERE entry = 39;
UPDATE skyfire_string SET content_loc2 = 'Vous étés: %s' WHERE entry = 40;
UPDATE skyfire_string SET content_loc2 = 'Visible' WHERE entry = 41;
UPDATE skyfire_string SET content_loc2 = 'Invisible' WHERE entry = 42;
UPDATE skyfire_string SET content_loc2 = 'Fait' WHERE entry = 43;
UPDATE skyfire_string SET content_loc2 = 'Vous' WHERE entry = 44;
UPDATE skyfire_string SET content_loc2 = '<Inconnu>' WHERE entry = 45;
UPDATE skyfire_string SET content_loc2 = '<Erreur>' WHERE entry = 46;
UPDATE skyfire_string SET content_loc2 = '<Personnage inexistant>' WHERE entry = 47;
UPDATE skyfire_string SET content_loc2 = 'INCONNU' WHERE entry = 48;
UPDATE skyfire_string SET content_loc2 = 'Vous devez avoir le niveau %u pour entrer.' WHERE entry = 49;
UPDATE skyfire_string SET content_loc2 = 'Vous devez avoir le niveau %u et avoir l\'objet %s pour entrer.' WHERE entry = 50;
UPDATE skyfire_string SET content_loc2 = 'Bonjour ! Pret pour l\'entrainement ?' WHERE entry = 51;
UPDATE skyfire_string SET content_loc2 = 'Nombre d\'objets invalide (%u) pour l\'objet %u' WHERE entry = 52;
UPDATE skyfire_string SET content_loc2 = 'Le courrier ne peut pas contenir plus de %u objets' WHERE entry = 53;
UPDATE skyfire_string SET content_loc2 = 'Les nouveaux mots de passe ne correspondent pas' WHERE entry = 54;
UPDATE skyfire_string SET content_loc2 = 'Votre mot de passe ne peut pas depasser 16 caracteres (limite du client). Mot de passe inchangé !' WHERE entry = 55;
UPDATE skyfire_string SET content_loc2 = 'Message de la journée: %s' WHERE entry = 56;

UPDATE skyfire_string SET content_loc2 = 'Utilisation de la BDD World: %s' WHERE entry = 57;
UPDATE skyfire_string SET content_loc2 = 'Utilisation de la bibliotheque de scripts: %s' WHERE entry = 58;
UPDATE skyfire_string SET content_loc2 = 'Utilisation des scripts ÉvennementAI: %s' WHERE entry = 59;
UPDATE skyfire_string SET content_loc2 = 'Joueurs en ligne: %u (max: %u)' WHERE entry = 60;
UPDATE skyfire_string SET content_loc2 = 'Jusqu\'a expansion %u permise maintenant.' WHERE entry = 61;
UPDATE skyfire_string SET content_loc2 = 'Annonce générale:' WHERE entry = 100;
UPDATE skyfire_string set content_loc2 = 'Carte: %u (%s) Zone: %u (%s) Espace: %u (%s) Phase: %u X: %f Y: %f Z: %f Orientation: %f grid[%u,%u]cell[%u,%u] ID de l''instance: %u  ZoneX: %f ZoneY: %f GroundZ: %f FloorZ: %f données de Hauteur (Carte: %u VMap: %u)' WHERE entry = 101;


UPDATE skyfire_string SET content_loc2 = '%s vient tout juste d\'etre teleporte.' WHERE entry = 102;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas téléporter un joueur dans une instance si vous n\'étés pas chef de son groupe.' WHERE entry = 103;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas aller dans l\'instance du joueur car vous étés actuellement dans un autre groupe.' WHERE entry = 104;
UPDATE skyfire_string SET content_loc2 = 'Vous pouvez aller dans l\'instance du joueur sans etre dans son groupe, seulement si vous activez le mode MJ.' WHERE entry = 105;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas vous téléporter vers le joueur %s d\'une instance a une autre.' WHERE entry = 106;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas téléporter le joueur %s d\'une instance a une autre.' WHERE entry = 107;
UPDATE skyfire_string SET content_loc2 = 'Vous invoquez %s%s.' WHERE entry = 108;
UPDATE skyfire_string SET content_loc2 = 'Vous étés invoqué par %s.' WHERE entry = 109;
UPDATE skyfire_string SET content_loc2 = 'Vous téléportez %s%s vers %s.' WHERE entry = 110;
UPDATE skyfire_string SET content_loc2 = 'Vous venez d\'être téléporte par %s.' WHERE entry = 111;
UPDATE skyfire_string SET content_loc2 = 'Le joueur (%s) n\'existe pas.' WHERE entry = 112;
UPDATE skyfire_string SET content_loc2 = 'Vous apparaissez a l\'emplacement de %s.' WHERE entry = 113;
UPDATE skyfire_string SET content_loc2 = '%s apparait sur votre emplacement.' WHERE entry = 114;
UPDATE skyfire_string SET content_loc2 = 'Valeurs incorrectes.' WHERE entry = 115;
UPDATE skyfire_string SET content_loc2 = 'Aucun personnage sélectionné.' WHERE entry = 116;
UPDATE skyfire_string SET content_loc2 = '%s n\'est pas dans un groupe.' WHERE entry = 117;
UPDATE skyfire_string SET content_loc2 = 'Vous changez les PV de %s a %i/%i.' WHERE entry = 118;
UPDATE skyfire_string SET content_loc2 = '%s a changé vos PV a %i/%i.' WHERE entry = 119;
UPDATE skyfire_string SET content_loc2 = 'Vous changez la MANA de %s a %i/%i.' WHERE entry = 120;
UPDATE skyfire_string SET content_loc2 = '%s a changé votre MANA a %i/%i.' WHERE entry = 121;
UPDATE skyfire_string SET content_loc2 = 'Vous changez l\'Énergie de %s a %i/%i.' WHERE entry = 122;
UPDATE skyfire_string SET content_loc2 = '%s a changé votre Énergie a %i/%i.' WHERE entry = 123;
UPDATE skyfire_string SET content_loc2 = 'Énergie actuelle: %u' WHERE entry = 124;
UPDATE skyfire_string SET content_loc2 = 'Vous changez la RAGE de %s a %i/%i.' WHERE entry = 125;
UPDATE skyfire_string SET content_loc2 = '%s a changé votre RAGE a %i/%i.' WHERE entry = 126;
UPDATE skyfire_string SET content_loc2 = 'Vous avez changé le niveau de %s a %i.' WHERE entry = 127;
UPDATE skyfire_string SET content_loc2 = 'GUID %i, faction est %i, flags est %i, npcflag est %i, DY flag est %i' WHERE entry = 128;
UPDATE skyfire_string SET content_loc2 = 'Mauvaise faction: %u (Non trouvée dans factiontemplate.dbc).' WHERE entry = 129;
UPDATE skyfire_string SET content_loc2 = 'Vous avez changé GUID=%i, faction a %i, flags a %i, npcflag a %i, dyflag a %i.' WHERE entry = 130;
UPDATE skyfire_string SET content_loc2 = 'Vous avez changé le spellflatid=%i, val= %i, mark= %i de %s.' WHERE entry = 131;
UPDATE skyfire_string SET content_loc2 = '%s a changé votre spellflatid=%i, val= %i, mark =%i.' WHERE entry = 132;
UPDATE skyfire_string SET content_loc2 = '%s a maintenant accès a tous les trajets aeriens (jusqu\'a sa déconnexion).' WHERE entry = 133;
UPDATE skyfire_string SET content_loc2 = '%s n\'a maintenant plus accès a tous les trajets aeriens (seuls ceux visites lui sont accèssibles).' WHERE entry = 134;
UPDATE skyfire_string SET content_loc2 = '%s vous a donne l\'accès a tous les trajets aeriens (jusqu\'a votre déconnexion).' WHERE entry = 135;
UPDATE skyfire_string SET content_loc2 = '%s vous a retire l\'accès a tous les trajets aeriens (seuls ceux visites vous sont accèssibles).' WHERE entry = 136;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié toutes les vitesses a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 137;
UPDATE skyfire_string SET content_loc2 = '%s a modifié toutes vos vitesses a %2.2f par rapport a la normale.' WHERE entry = 138;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la vitesse a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 139;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre vitesse a %2.2f par rapport a la normale.' WHERE entry = 140;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la vitesse de nage a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 141;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre vitesse de nage a %2.2f par rapport a la normale.' WHERE entry = 142;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la vitesse de recul a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 143;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre vitesse recul a %2.2f par rapport a la normale.' WHERE entry = 144;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la vitesse de vol a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 145;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre vitesse de vol a %2.2f par rapport a la normale.' WHERE entry = 146;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la taille a %2.2f par rapport a la normale pour le joueur %s.' WHERE entry = 147;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre taille a %2.2f par rapport a la normale.' WHERE entry = 148;
UPDATE skyfire_string SET content_loc2 = 'Cette monture n\'existe pas.' WHERE entry = 149;
UPDATE skyfire_string SET content_loc2 = 'Vous donnez une monture a %s.' WHERE entry = 150;
UPDATE skyfire_string SET content_loc2 = '%s vous a donne une monture.' WHERE entry = 151;
UPDATE skyfire_string SET content_loc2 = 'UTILISATEUR1: %i, AJOUT: %i, DIF: %i' WHERE entry = 152;

UPDATE skyfire_string SET content_loc2 = 'Vous prenez tout l\'argent de %s.' WHERE entry = 153;
UPDATE skyfire_string SET content_loc2 = '%s vous a pris tout votre argent.' WHERE entry = 154;
UPDATE skyfire_string SET content_loc2 = 'Vous prenez %i piece(s) de cuivre a %s.' WHERE entry = 155;
UPDATE skyfire_string SET content_loc2 = '%s vous a pris %i piece(s) de cuivre.' WHERE entry = 156;
UPDATE skyfire_string SET content_loc2 = 'Vous donnez %i piece(s) de cuivre a %s.' WHERE entry = 157;
UPDATE skyfire_string SET content_loc2 = '%s vous a donne %i piece(s) de cuivre.' WHERE entry = 158;
UPDATE skyfire_string SET content_loc2 = 'Vous entendez le son %u.' WHERE entry = 159;
UPDATE skyfire_string SET content_loc2 = 'UTILISATEUR2: %i, AJOUT: %i, RESULTAT: %i' WHERE entry = 160;

UPDATE skyfire_string SET content_loc2 = 'Suppression du bit %i dans le champ %i.' WHERE entry = 161;
UPDATE skyfire_string SET content_loc2 = 'Ajout du bit %i dans le champ %i.' WHERE entry = 162;
UPDATE skyfire_string SET content_loc2 = 'La table de destinations de téléportation est vide !' WHERE entry = 163;
UPDATE skyfire_string SET content_loc2 = 'La destination de téléportation est introuvable !' WHERE entry = 164;
UPDATE skyfire_string SET content_loc2 = 'paramètre de recherche exige.' WHERE entry = 165;
UPDATE skyfire_string SET content_loc2 = 'Aucune destination ne correspond a votre recherche.' WHERE entry = 166;
UPDATE skyfire_string SET content_loc2 = 'Les destinations trouvées sont: %s' WHERE entry = 168;
UPDATE skyfire_string SET content_loc2 = 'Courrier envoyee %s' WHERE entry = 169;
UPDATE skyfire_string SET content_loc2 = 'Vous essayez d\'ecouter le son %u mais il n\'existe pas.' WHERE entry = 170;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez vous téléporter sur vous-meme!' WHERE entry = 171;
UPDATE skyfire_string SET content_loc2 = 'Commande de console du serveur' WHERE entry = 172;
UPDATE skyfire_string SET content_loc2 = 'Vous avez changé la puissance runique de %s a %i/%i.' WHERE entry = 173;
UPDATE skyfire_string SET content_loc2 = 'La puissance runique de %s a été changé a %i/%i.' WHERE entry = 174;
UPDATE skyfire_string SET content_loc2 = 'Niveau liquide: %f, profondeur: %f, type: %d, statut: %d' WHERE entry = 175;
UPDATE skyfire_string SET content_loc2 = 'Aucune selection.' WHERE entry = 200;
UPDATE skyfire_string SET content_loc2 = 'Objet GUID est: lowpart %u highpart %X' WHERE entry = 201;
UPDATE skyfire_string SET content_loc2 = 'Le nom etait trop long avec %i caracteres.' WHERE entry = 202;
UPDATE skyfire_string SET content_loc2 = 'Erreur, le nom ne peut contenir que les caracteres A-Z et a-z.' WHERE entry = 203;
UPDATE skyfire_string SET content_loc2 = 'Le surnom est trop long avec %i caracteres.' WHERE entry = 204;
UPDATE skyfire_string SET content_loc2 = 'Pas encore implante.' WHERE entry = 205;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' \'%s\' ajoute a la liste du vendeur avec maxcount \'%i\' et incrtime \'%i\' et extendedcost \'%i\'' WHERE entry = 206;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' introuvable dans la Base de données.' WHERE entry = 207;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' \'%s\' supprimé de la liste du vendeur.' WHERE entry = 208;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' introuvable dans la liste du vendeur.' WHERE entry = 209;
UPDATE skyfire_string SET content_loc2 = 'Les sorts de %s ont été réinitialisés.' WHERE entry = 211;
UPDATE skyfire_string SET content_loc2 = 'Les sorts de %s seront réinitialisés lors de la prochaine connexion.' WHERE entry = 212;
UPDATE skyfire_string SET content_loc2 = 'Les talents de %s ont été réinitialisés.' WHERE entry = 213;
UPDATE skyfire_string SET content_loc2 = 'Les talents de %s seront réinitialisés lors de la prochaine connexion.' WHERE entry = 214;
UPDATE skyfire_string SET content_loc2 = 'Vos sorts ont été réinitialisés.' WHERE entry = 215;
UPDATE skyfire_string SET content_loc2 = 'Vos talents ont été réinitialisés.' WHERE entry = 216;
UPDATE skyfire_string SET content_loc2 = 'paramètre \'%s\' inconnu pour la commande .reSET all. Donnez un nom correct de paramètre.' WHERE entry = 217;
UPDATE skyfire_string SET content_loc2 = 'Les sorts seront réinitialisés pour tous les joueurs en ligne. Reconnexion fortement recommande !' WHERE entry = 218;
UPDATE skyfire_string SET content_loc2 = 'Les talents seront réinitialisés pour tous les joueurs en ligne. Reconnexion fortement recommande !' WHERE entry = 219;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) Aucun point de passage trouvé.' WHERE entry = 220;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) Dernier point de passage introuvable.' WHERE entry = 221;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) Aucun point de passage trouvé - Utilisez \'wpguid\'. Maintenant essayez de le trouvér avec sa position...' WHERE entry = 222;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) Aucun point de passage trouvé - C\'est une erreur de base de données (single float).' WHERE entry = 223;
UPDATE skyfire_string SET content_loc2 = 'Créature sélectionnée ignoree - Le GUID fourni est en cours d\'utilisation.' WHERE entry = 224;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) introuvable' WHERE entry = 225;
UPDATE skyfire_string SET content_loc2 = 'Vous devez sélectionner un point de passage visible.' WHERE entry = 226;
UPDATE skyfire_string SET content_loc2 = 'Aucun point de passage visible trouvé.' WHERE entry = 227;
UPDATE skyfire_string SET content_loc2 = 'Impossible de créer un point de passage visible avec la créature d\'ID: %d.' WHERE entry = 228;
UPDATE skyfire_string SET content_loc2 = 'Tous les points de passage visibles ont été supprimés.' WHERE entry = 229;
UPDATE skyfire_string SET content_loc2 = 'Impossible de créer un point de passage de créature avec l\'ID: %d' WHERE entry = 230;
UPDATE skyfire_string SET content_loc2 = 'Aucun GUID fourni.' WHERE entry = 231;
UPDATE skyfire_string SET content_loc2 = 'Aucun numero de point de passage fourni.' WHERE entry = 232;
UPDATE skyfire_string SET content_loc2 = 'Un argument est requis pour \'%s\'.' WHERE entry = 233;
UPDATE skyfire_string SET content_loc2 = 'Point de passage %i ajoute au GUID: %d' WHERE entry = 234;
UPDATE skyfire_string SET content_loc2 = 'Point de passage %d ajoute.' WHERE entry = 235;
UPDATE skyfire_string SET content_loc2 = 'Point de passage changé.' WHERE entry = 236;
UPDATE skyfire_string SET content_loc2 = 'Point de passage %s modifié.' WHERE entry = 237;
UPDATE skyfire_string SET content_loc2 = 'Points de passage exportes avec succès.' WHERE entry = 238;
UPDATE skyfire_string SET content_loc2 = 'Aucun point de passage trouvé dans la base de données.' WHERE entry = 239;
UPDATE skyfire_string SET content_loc2 = 'Fichier importé.' WHERE entry = 240;
UPDATE skyfire_string SET content_loc2 = 'Point de passage supprimé.' WHERE entry = 241;
UPDATE skyfire_string SET content_loc2 = 'Attention: impossible de supprimér le point de passage du monde avec ID: %d' WHERE entry = 242;
UPDATE skyfire_string SET content_loc2 = 'Cela arrive lorsque le point de passage est trop loin de votre personnage.' WHERE entry = 243;
UPDATE skyfire_string SET content_loc2 = 'Le point de passage a été supprimé de la base de données, mais pas depuis ce monde.' WHERE entry = 244;
UPDATE skyfire_string SET content_loc2 = 'Ils disparaitront apres un redémarrage du serveur.' WHERE entry = 245;
UPDATE skyfire_string SET content_loc2 = 'Point de passage %d: Info pour la créature: %s, GUID: %d' WHERE entry = 246;
UPDATE skyfire_string SET content_loc2 = 'Temps d\'attente: %d' WHERE entry = 247;
UPDATE skyfire_string SET content_loc2 = 'Modele %d: %d' WHERE entry = 248;
UPDATE skyfire_string SET content_loc2 = 'Emotion: %d' WHERE entry = 249;
UPDATE skyfire_string SET content_loc2 = 'Sort: %d' WHERE entry = 250;
UPDATE skyfire_string SET content_loc2 = 'Texte %d (ID: %i): %s' WHERE entry = 251;
UPDATE skyfire_string SET content_loc2 = 'ScriptIA: %s' WHERE entry = 252;
UPDATE skyfire_string SET content_loc2 = 'changement force du nom du joueur %s a la prochaine connexion.' WHERE entry = 253;
UPDATE skyfire_string SET content_loc2 = 'changement force du nom du joueur %s (GUID #%u) a la prochaine connexion.' WHERE entry = 254;
UPDATE skyfire_string SET content_loc2 = 'Point de passage de créature (GUID: %u) introuvable.' WHERE entry = 255;
UPDATE skyfire_string SET content_loc2 = 'Impossible de trouvér le PNJ...' WHERE entry = 256;
UPDATE skyfire_string SET content_loc2 = 'Type de mouvement de créature modifié a \'%s\', points de passage supprimés (si existants).' WHERE entry = 257;
UPDATE skyfire_string SET content_loc2 = 'Type de mouvement de créature modifié a \'%s\', points de passage non supprimés.' WHERE entry = 258;
UPDATE skyfire_string SET content_loc2 = 'Valeur incorrecte, utilisez ON ou OFF.' WHERE entry = 259;
UPDATE skyfire_string SET content_loc2 = 'Valeur sauvegardee.' WHERE entry = 260;
UPDATE skyfire_string SET content_loc2 = 'Valeur sauvegardee, nettoyez le cache de votre client.' WHERE entry = 261;
UPDATE skyfire_string SET content_loc2 = 'Areatrigger ID %u non trouvé !' WHERE entry = 262;
UPDATE skyfire_string SET content_loc2 = 'Carte ou coordonnées de destination invalides (X: %f Y: %f MapId: %u).' WHERE entry = 263;
UPDATE skyfire_string SET content_loc2 = 'Coordonnées de zone invalides (X: %f Y: %f AreaId: %u)' WHERE entry = 264;
UPDATE skyfire_string SET content_loc2 = 'La zone %u (%s) est une partie de l\'instance %u (%s)' WHERE entry = 265;
UPDATE skyfire_string SET content_loc2 = 'Rien n\'a été trouvé !' WHERE entry = 266;
UPDATE skyfire_string SET content_loc2 = 'Objet introuvable !' WHERE entry = 267;
UPDATE skyfire_string SET content_loc2 = 'Créature introuvable !' WHERE entry = 268;
UPDATE skyfire_string SET content_loc2 = 'Attention: La recherche a donnée plusieurs resultats, vous devriez etre teleporte sur la premiere créature trouvée dans la base de données.' WHERE entry = 269;
UPDATE skyfire_string SET content_loc2 = 'Créature supprimée.' WHERE entry = 270;
UPDATE skyfire_string SET content_loc2 = 'Créature deplacee.' WHERE entry = 271;
UPDATE skyfire_string SET content_loc2 = 'La créature (GUID: %u) doit etre sur la meme carte que le joueur !' WHERE entry = 272;
UPDATE skyfire_string SET content_loc2 = 'Game Object (GUID: %u) introuvable.' WHERE entry = 273;
UPDATE skyfire_string SET content_loc2 = 'Game Object (GUID: %u) a des references sur une créature introuvable %u, impossible de le supprimér.' WHERE entry = 274;
UPDATE skyfire_string SET content_loc2 = 'Game Object (GUID: %u) supprimé.' WHERE entry = 275;
UPDATE skyfire_string SET content_loc2 = 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) tournA' WHERE entry = 276;
UPDATE skyfire_string SET content_loc2 = 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) deplace.' WHERE entry = 277;
UPDATE skyfire_string SET content_loc2 = 'Vous devez sélectionner un vendeur' WHERE entry = 278;
UPDATE skyfire_string SET content_loc2 = 'Vous devez indiquer un ID pour l\'Équipement' WHERE entry = 279;
UPDATE skyfire_string SET content_loc2 = 'Le vendeur possède trop d\'Équipements (max 128).' WHERE entry = 280;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas vous kicker vous-meme, deconnectéz-vous plutot.' WHERE entry = 281;
UPDATE skyfire_string SET content_loc2 = 'Joueur %s kicke.' WHERE entry = 282;
UPDATE skyfire_string SET content_loc2 = 'Acceptation des chuchotements: %s' WHERE entry = 284;
UPDATE skyfire_string SET content_loc2 = 'Acceptation des chuchotements: ON' WHERE entry = 285;
UPDATE skyfire_string SET content_loc2 = 'Acceptation des chuchotements: OFF' WHERE entry = 286;
UPDATE skyfire_string SET content_loc2 = 'Créature (GUID: %u) introuvable' WHERE entry = 287;
UPDATE skyfire_string SET content_loc2 = 'Nombre de tickets: %i Affichage des nouveaux tickets: %s' WHERE entry = 288;
UPDATE skyfire_string SET content_loc2 = 'Nouveau ticket de %s.' WHERE entry = 289;
UPDATE skyfire_string SET content_loc2 = 'Ticket de %s (Derniere mise a jour: %s): %s' WHERE entry = 290;

UPDATE skyfire_string SET content_loc2 = 'Affichage des nouveaux tickets: ON' WHERE entry = 291;
UPDATE skyfire_string SET content_loc2 = 'Affichage des nouveaux tickets: OFF' WHERE entry = 292;
UPDATE skyfire_string SET content_loc2 = 'Ticket %i inexistant.' WHERE entry = 293;
UPDATE skyfire_string SET content_loc2 = 'Tous les tickets ont été supprimés.' WHERE entry = 294;
UPDATE skyfire_string SET content_loc2 = 'Ticket du joueur %s supprimé.' WHERE entry = 295;
UPDATE skyfire_string SET content_loc2 = 'Ticket supprimé.' WHERE entry = 296;
UPDATE skyfire_string SET content_loc2 = 'Distance d\'apparition changée a : %f' WHERE entry = 297;
UPDATE skyfire_string SET content_loc2 = 'Temps d\'apparition changé a : %i' WHERE entry = 298;
UPDATE skyfire_string SET content_loc2 = 'L\'honneur de %s a été modifié a %u !' WHERE entry = 299;
UPDATE skyfire_string SET content_loc2 = 'Votre tchat a été désactive pour %u minutes.' WHERE entry = 300;
UPDATE skyfire_string SET content_loc2 = 'Vous avez désactive le tchat de %s pour %u minutes.' WHERE entry = 301;
UPDATE skyfire_string SET content_loc2 = 'Le tchat du joueur est déja active.' WHERE entry = 302;
UPDATE skyfire_string SET content_loc2 = 'Votre tchat a été active.' WHERE entry = 303;
UPDATE skyfire_string SET content_loc2 = 'Vous avez active le tchat de %s.' WHERE entry = 304;
UPDATE skyfire_string SET content_loc2 = 'La faction de réputation %s (%u) de %s a été modifié a %5d !' WHERE entry = 305;
UPDATE skyfire_string SET content_loc2 = 'Les points d\'arène de %s ont été modifiés a %u !' WHERE entry = 306;
UPDATE skyfire_string SET content_loc2 = 'Aucune faction trouvé.' WHERE entry = 307;
UPDATE skyfire_string SET content_loc2 = 'Faction %i inconnu !' WHERE entry = 308;
UPDATE skyfire_string SET content_loc2 = 'paramètre %s invalide' WHERE entry = 309;
UPDATE skyfire_string SET content_loc2 = 'delta doit etre compris entre 0 et %d (inclus)' WHERE entry = 310;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hfaction:%d|h[%s]|h|r' WHERE entry = 311;
UPDATE skyfire_string SET content_loc2 = '[Visible]' WHERE entry = 312;
UPDATE skyfire_string SET content_loc2 = '[En guerre]' WHERE entry = 313;
UPDATE skyfire_string SET content_loc2 = '[Paix obligatoire]' WHERE entry = 314;
UPDATE skyfire_string SET content_loc2 = '[Cache]' WHERE entry = 315;
UPDATE skyfire_string SET content_loc2 = '[Invisible obligatoire]' WHERE entry = 316;
UPDATE skyfire_string SET content_loc2 = '[Inactif]' WHERE entry = 317;
UPDATE skyfire_string SET content_loc2 = 'Détéste' WHERE entry = 318;
UPDATE skyfire_string SET content_loc2 = 'Hostile' WHERE entry = 319;
UPDATE skyfire_string SET content_loc2 = 'Inamical' WHERE entry = 320;
UPDATE skyfire_string SET content_loc2 = 'Neutre' WHERE entry = 321;
UPDATE skyfire_string SET content_loc2 = 'Amical' WHERE entry = 322;
UPDATE skyfire_string SET content_loc2 = 'Honore' WHERE entry = 323;
UPDATE skyfire_string SET content_loc2 = 'Revere' WHERE entry = 324;
UPDATE skyfire_string SET content_loc2 = 'Exalte' WHERE entry = 325;
UPDATE skyfire_string SET content_loc2 = 'La faction %s (%u) ne peut pas avoir de réputation.' WHERE entry = 326;
UPDATE skyfire_string SET content_loc2 = '[Aucune réputation]' WHERE entry = 327;
UPDATE skyfire_string SET content_loc2 = 'Personnages sur le compte %s (Id: %u)' WHERE entry = 328;
UPDATE skyfire_string SET content_loc2 = '%s (GUID %u)' WHERE entry = 329;
UPDATE skyfire_string SET content_loc2 = 'Aucun joueur trouvé !' WHERE entry = 330;
UPDATE skyfire_string SET content_loc2 = 'Extended item cost %u inexistant' WHERE entry = 331;
UPDATE skyfire_string SET content_loc2 = 'Mode MJ active' WHERE entry = 332;
UPDATE skyfire_string SET content_loc2 = 'Mode MJ désactive' WHERE entry = 333;
UPDATE skyfire_string SET content_loc2 = 'Logo Tchat MJ active' WHERE entry = 334;
UPDATE skyfire_string SET content_loc2 = 'Logo Tchat MJ désactive' WHERE entry = 335;
UPDATE skyfire_string SET content_loc2 = 'Vous reparez tous les Équipements de %s.' WHERE entry = 336;
UPDATE skyfire_string SET content_loc2 = 'Tous vos Équipements ont été repares par %s.' WHERE entry = 337;
UPDATE skyfire_string SET content_loc2 = 'Vous configurez le mode Marche-sur-eau a %s pour %s.' WHERE entry = 338;
UPDATE skyfire_string SET content_loc2 = 'Votre mode Marche-sur-eau a été configuré a %s par %s.' WHERE entry = 339;
UPDATE skyfire_string SET content_loc2 = '%s est en train de vous suivre.' WHERE entry = 340;
UPDATE skyfire_string SET content_loc2 = '%s ne vous suit plus.' WHERE entry = 341;
UPDATE skyfire_string SET content_loc2 = '%s n\'est plus en train de vous suivre.' WHERE entry = 342;
UPDATE skyfire_string SET content_loc2 = 'La créature (Entry: %u) ne peut pas etre domptee.' WHERE entry = 343;
UPDATE skyfire_string SET content_loc2 = 'Vous possèdez déja un familier.' WHERE entry = 344;
UPDATE skyfire_string SET content_loc2 = 'Customisation forcee du Joueur %s a la prochaine connexion.' WHERE entry = 345;
UPDATE skyfire_string SET content_loc2 = 'Customisation forcee du joueur %s (GUID #%u) a la prochaine connexion.' WHERE entry = 346;
UPDATE skyfire_string SET content_loc2 = 'TaxiNode d\'ID %u introuvable !' WHERE entry = 347;
UPDATE skyfire_string SET content_loc2 = 'Le Gameobject (Entry: %u) possède un champ data invalide, et ne peut donc pas etre implante.' WHERE entry = 348;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Message Systeme]:|r Scripts recharges' WHERE entry = 400;
UPDATE skyfire_string SET content_loc2 = 'Vous modifiéz le niveau de securite du compte %s a %i.' WHERE entry = 401;
UPDATE skyfire_string SET content_loc2 = '%s a modifié votre niveau de securite a %i.' WHERE entry = 402;
UPDATE skyfire_string SET content_loc2 = 'Vous avez un niveau de securite trop bas pour cela.' WHERE entry = 403;
UPDATE skyfire_string SET content_loc2 = 'Mouvements de la créature désactivés.' WHERE entry = 404;
UPDATE skyfire_string SET content_loc2 = 'Mouvements de la créature activés.' WHERE entry = 405;
UPDATE skyfire_string SET content_loc2 = 'La météorologie ne peut pas etre changée dans cette zone.' WHERE entry = 406;
UPDATE skyfire_string SET content_loc2 = 'Le systeme météorologique est désactive.' WHERE entry = 407;
UPDATE skyfire_string SET content_loc2 = '%s est banni pendant %s. Motif: %s.' WHERE entry = 408;
UPDATE skyfire_string SET content_loc2 = '%s est banni de maniere permanente pour %s.' WHERE entry = 409;
UPDATE skyfire_string SET content_loc2 = '%s %s introuvable.' WHERE entry = 410;
UPDATE skyfire_string SET content_loc2 = '%s Débanni.' WHERE entry = 411;
UPDATE skyfire_string SET content_loc2 = 'Il est survenu une erreur lors du Débanissement de %s.' WHERE entry = 412;
UPDATE skyfire_string SET content_loc2 = 'Compte inexistant: %s' WHERE entry = 413;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a aucun personnage correspondant.' WHERE entry = 414;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a aucune adresse IP correspondante dans la liste des bannis.' WHERE entry = 415;
UPDATE skyfire_string SET content_loc2 = 'Le compte %s n\'a jamais été banni.' WHERE entry = 416;
UPDATE skyfire_string SET content_loc2 = 'Historique de bannissement du compte %s:' WHERE entry = 417;
UPDATE skyfire_string SET content_loc2 = 'Date de bannissement: %s Duree: %s Etat: %s Motif: %s Par: %s' WHERE entry = 418;
UPDATE skyfire_string SET content_loc2 = 'Inf.' WHERE entry = 419;
UPDATE skyfire_string SET content_loc2 = 'Jamais' WHERE entry = 420;
UPDATE skyfire_string SET content_loc2 = 'Oui' WHERE entry = 421;
UPDATE skyfire_string SET content_loc2 = 'Non' WHERE entry = 422;

UPDATE skyfire_string SET content_loc2 = 'IP: %s Date ban: %s Date Déban: %s Temps restant: %s Raison: %s Banni par: %s' WHERE entry = 423;

UPDATE skyfire_string SET content_loc2 = 'Il n\'y a pas d\'ip bannie correspondante.' WHERE entry = 424;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a pas de compte correspondant.' WHERE entry = 425;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a pas de compte banni correspondant au nom de personnage donne.' WHERE entry = 426;
UPDATE skyfire_string SET content_loc2 = 'Les IP suivantes correspondent a votre recherche:' WHERE entry = 427;
UPDATE skyfire_string SET content_loc2 = 'Les comptes suivant correspondent a votre requête:' WHERE entry = 428;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris plusieurs sorts/compéténces.' WHERE entry = 429;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris tous les sorts de votre classe.' WHERE entry = 430;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris tous les talents de votre classe.' WHERE entry = 431;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris toutes les langues.' WHERE entry = 432;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris toutes les compéténces de metier et recettes.' WHERE entry = 433;
UPDATE skyfire_string SET content_loc2 = 'Impossible de trouvér \'%s\'.' WHERE entry = 434;
UPDATE skyfire_string SET content_loc2 = 'ID de l\'Équipement invalide: %u' WHERE entry = 435;
UPDATE skyfire_string SET content_loc2 = 'Aucun Équipement trouvé !' WHERE entry = 436;
UPDATE skyfire_string SET content_loc2 = 'ID de l\'objet invalide: %u' WHERE entry = 437;
UPDATE skyfire_string SET content_loc2 = 'Équipements %u trouvés: %u (inventaire %u courrier %u autel %u guilde %u)' WHERE entry = 438;
UPDATE skyfire_string SET content_loc2 = 'Objets %u trouvés: %u' WHERE entry = 439;
UPDATE skyfire_string SET content_loc2 = 'ID de créature invalide: %u' WHERE entry = 440;
UPDATE skyfire_string SET content_loc2 = 'Créatures %u trouvées: %u' WHERE entry = 441;
UPDATE skyfire_string SET content_loc2 = 'Aucune région trouvée !' WHERE entry = 442;
UPDATE skyfire_string SET content_loc2 = 'Aucun SET d\'Équipements trouvé !' WHERE entry = 443;
UPDATE skyfire_string SET content_loc2 = 'Aucune compéténce trouvée !' WHERE entry = 444;
UPDATE skyfire_string SET content_loc2 = 'Aucun sort trouvé !' WHERE entry = 445;
UPDATE skyfire_string SET content_loc2 = 'Aucune quête trouvée !' WHERE entry = 446;
UPDATE skyfire_string SET content_loc2 = 'Aucune créature trouvée !' WHERE entry = 447;
UPDATE skyfire_string SET content_loc2 = 'Aucun objet trouvé !' WHERE entry = 448;
UPDATE skyfire_string SET content_loc2 = 'cimetière #%u inexistant.' WHERE entry = 449;
UPDATE skyfire_string SET content_loc2 = 'Le cimetière #%u est déja lie a la zone #%u (actuelle).' WHERE entry = 450;
UPDATE skyfire_string SET content_loc2 = 'Le cimetière #%u est lie a la zone #%u (actuelle).' WHERE entry = 451;
UPDATE skyfire_string SET content_loc2 = 'Le cimetière #%u ne peut pas etre lie a la sous-zone ou la zone est inexistante #%u (erreur interne).' WHERE entry = 452;
UPDATE skyfire_string SET content_loc2 = 'Aucune faction dans le cimetière d\'id= #%u, corrigez votre BDD.' WHERE entry = 454;
UPDATE skyfire_string SET content_loc2 = 'equipe invalide, corrigez votre BDD.' WHERE entry = 455;
UPDATE skyfire_string SET content_loc2 = 'chaque' WHERE entry = 456;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance' WHERE entry = 457;
UPDATE skyfire_string SET content_loc2 = 'La Horde' WHERE entry = 458;
UPDATE skyfire_string SET content_loc2 = 'Le cimetière #%u (faction: %s) est le plus proche lie a la zone #%u.' WHERE entry = 459;
UPDATE skyfire_string SET content_loc2 = 'La zone #%u n\'a aucun cimetière lie.' WHERE entry = 460;
UPDATE skyfire_string SET content_loc2 = 'La zone #%u n\'a aucun cimetière lie pour la faction: %s.' WHERE entry = 461;
UPDATE skyfire_string SET content_loc2 = 'L\'emplacement de téléportation existe déja !' WHERE entry = 462;
UPDATE skyfire_string SET content_loc2 = 'Emplacement de téléportation ajoute.' WHERE entry = 463;
UPDATE skyfire_string SET content_loc2 = 'Emplacement de téléportation NON ajoute: erreur dans la base de données.' WHERE entry = 464;
UPDATE skyfire_string SET content_loc2 = 'Emplacement de téléportation supprimé.' WHERE entry = 465;
UPDATE skyfire_string SET content_loc2 = 'Aucun TaxiNode trouvé !' WHERE entry = 466;
UPDATE skyfire_string SET content_loc2 = 'La cible a %d auras:' WHERE entry = 467;
UPDATE skyfire_string SET content_loc2 = 'id: %d eff: %d type: %d duree: %d duree max: %d nom: %s%s%s lanceur de sort: %s %u' WHERE entry = 468;
UPDATE skyfire_string SET content_loc2 = 'La cible a %d auras de type %d:' WHERE entry = 469;
UPDATE skyfire_string SET content_loc2 = 'id: %d eff: %d nom: %d' WHERE entry = 470;
UPDATE skyfire_string SET content_loc2 = 'quête %u introuvable.' WHERE entry = 471;
UPDATE skyfire_string SET content_loc2 = 'La quête %u est demarree par un Équipement. Pour un fonctionnement correct, merci d\'ajouter l\'Équipement dans l\'inventaire et de demarrer la quête normalement: .additem %u' WHERE entry = 472;
UPDATE skyfire_string SET content_loc2 = 'quête supprimée.' WHERE entry = 473;
UPDATE skyfire_string SET content_loc2 = '[Recompense]' WHERE entry = 474;
UPDATE skyfire_string SET content_loc2 = '[Termine]' WHERE entry = 475;
UPDATE skyfire_string SET content_loc2 = '[Actif]' WHERE entry = 476;
UPDATE skyfire_string SET content_loc2 = 'Mode de vol de %s: %s' WHERE entry = 477;
UPDATE skyfire_string SET content_loc2 = 'Opcode %u envoye a %s' WHERE entry = 478;
UPDATE skyfire_string SET content_loc2 = 'Personnage charge avec succès !' WHERE entry = 479;
UPDATE skyfire_string SET content_loc2 = 'Échec lors du chargement du personnage !' WHERE entry = 480;
UPDATE skyfire_string SET content_loc2 = 'Personnage exporte avec succès !' WHERE entry = 481;
UPDATE skyfire_string SET content_loc2 = 'Échec lors de l\'exportation du personnage !' WHERE entry = 482;
UPDATE skyfire_string SET content_loc2 = 'Sort %u défaillant et impossible a incanter ou apprendre !' WHERE entry = 483;
UPDATE skyfire_string SET content_loc2 = 'La compéténce %u (%s) pour le joueur %s a été mise a %u avec un maximum de %u (sans bonus (talents) permanent).' WHERE entry = 484;
UPDATE skyfire_string SET content_loc2 = 'Le joueur %s doit possèder la compéténce %u (%s) avant d\'utiliser cette commande.' WHERE entry = 485;
UPDATE skyfire_string SET content_loc2 = 'ID de compéténce invalide (%u)' WHERE entry = 486;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris les sorts/compéténces de base du MJ.' WHERE entry = 487;
UPDATE skyfire_string SET content_loc2 = 'Vous connaissez déja ce sort.' WHERE entry = 488;
UPDATE skyfire_string SET content_loc2 = 'La cible (%s) connait déja ce sort.' WHERE entry = 489;
UPDATE skyfire_string SET content_loc2 = '%s ne connait pas ce sort.' WHERE entry = 490;
UPDATE skyfire_string SET content_loc2 = 'Vous avez déja oublie ce sort.' WHERE entry = 491;
UPDATE skyfire_string SET content_loc2 = 'Tous les temps de rechargement des sorts ont été supprimés pour %s.' WHERE entry = 492;
UPDATE skyfire_string SET content_loc2 = 'Le temps de rechargement du sort %u a été supprimé pour %s.' WHERE entry = 493;
UPDATE skyfire_string SET content_loc2 = 'Commande: Additem, ID de l\'Équipement = %i, quantité = %i' WHERE entry = 494;
UPDATE skyfire_string SET content_loc2 = 'Commande: AdditemSET , ID du SET = %i' WHERE entry = 495;
UPDATE skyfire_string SET content_loc2 = 'Suppression de l\'Équipement d\'ID = %i, quantité = %i de %s' WHERE entry = 496;
UPDATE skyfire_string SET content_loc2 = 'Impossible de créer l\'Équipement \'%i\' (quantité: %i)' WHERE entry = 497;
UPDATE skyfire_string SET content_loc2 = 'Vous devez specifier un nom de guilde !' WHERE entry = 498;
UPDATE skyfire_string SET content_loc2 = 'Joueur introuvable !' WHERE entry = 499;
UPDATE skyfire_string SET content_loc2 = 'Le joueur possède déja une guilde !' WHERE entry = 500;
UPDATE skyfire_string SET content_loc2 = 'Échec lors de la creation de la guilde (déja existante ?)' WHERE entry = 501;
UPDATE skyfire_string SET content_loc2 = 'Aucun Équipement du SET \'%u\' n\'a été trouvé.' WHERE entry = 502;
UPDATE skyfire_string SET content_loc2 = 'La distance est: (3D) %f (2D) %f yards.' WHERE entry = 503;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' \'%s\' Emplacement de l\'Équipement %i' WHERE entry = 504;
UPDATE skyfire_string SET content_loc2 = 'Équipement \'%i\' inexistant.' WHERE entry = 505;
UPDATE skyfire_string SET content_loc2 = 'L\'Équipement \'%i\' \'%s\' a été ajoute a l\'emplacement %i' WHERE entry = 506;
UPDATE skyfire_string SET content_loc2 = 'Échec lors de la sauvegarde d\'un Équipement !' WHERE entry = 507;

UPDATE skyfire_string SET content_loc2 = '%d - Propriétaire: %s (guid: %u account: %u ) %s' WHERE entry = 508;
UPDATE skyfire_string SET content_loc2 = '%d - Expéditeur: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s' WHERE entry = 509;
UPDATE skyfire_string SET content_loc2 = '%d - Propriétaire: %s (guid: %u account: %u ) %s' WHERE entry = 510;


UPDATE skyfire_string SET content_loc2 = 'Mauvais type de lien !' WHERE entry = 511;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE entry = 512;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' WHERE entry = 513;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hcréature_entry:%d|h[%s]|h|r ' WHERE entry = 514;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hcréature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry = 515;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r' WHERE entry = 516;
UPDATE skyfire_string SET content_loc2 = '%d (Entry: %d) - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry = 517;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|HitemSET :%d|h[%s %s]|h|r ' WHERE entry = 518;
UPDATE skyfire_string SET content_loc2 = '|cffffffff|Htele:%s|h[%s]|h|r ' WHERE entry = 519;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hspell:%d|h[%s]|h|r ' WHERE entry = 520;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' WHERE entry = 521;
UPDATE skyfire_string SET content_loc2 = 'Gameobject (Entry: %u) introuvable.' WHERE entry = 522;
UPDATE skyfire_string SET content_loc2 = '>> Game Object %s (GUID: %u) %f %f %f. Orientation %f.' WHERE entry = 523;

UPDATE skyfire_string SET content_loc2 = 'Objet sélectionné: |cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u X: %f Y: %f Z: %f Carte: %u Orientation: %f Phasemask %u' WHERE entry = 524;

UPDATE skyfire_string SET content_loc2 = '>> Le Game Object \'%i\' (%s) (GUID: %i) a été ajoute a \'%f %f %f\'.' WHERE entry = 525;
UPDATE skyfire_string SET content_loc2 = '%s (lowguid: %u) pile de générateurs de mouvements:' WHERE entry = 526;
UPDATE skyfire_string SET content_loc2 = 'Au repos' WHERE entry = 527;
UPDATE skyfire_string SET content_loc2 = 'aléatoire' WHERE entry = 528;
UPDATE skyfire_string SET content_loc2 = 'Point de passage' WHERE entry = 529;
UPDATE skyfire_string SET content_loc2 = 'Animal aléatoire' WHERE entry = 530;
UPDATE skyfire_string SET content_loc2 = 'Confus' WHERE entry = 531;
UPDATE skyfire_string SET content_loc2 = 'Cible sur le joueur %s (lowguid %u)' WHERE entry = 532;
UPDATE skyfire_string SET content_loc2 = 'Cible sur la créature %s (lowguid %u)' WHERE entry = 533;
UPDATE skyfire_string SET content_loc2 = 'Cible sur <NULL>' WHERE entry = 534;
UPDATE skyfire_string SET content_loc2 = 'Mouvement domestique a (X: %f Y: %f Z: %f)' WHERE entry = 535;
UPDATE skyfire_string SET content_loc2 = 'Mouvement domestique utilise pour le joueur ?!?' WHERE entry = 536;
UPDATE skyfire_string SET content_loc2 = 'Déplacement de vol' WHERE entry = 537;
UPDATE skyfire_string SET content_loc2 = 'Générateur de mouvement inconnu (%u)' WHERE entry = 538;
UPDATE skyfire_string SET content_loc2 = 'PNJ sélectionné GUID: %u. Faction: %u. npcFlags: %u. Entry: %u. DisplayID: %u (Native: %u).' WHERE entry = 539;

UPDATE skyfire_string SET content_loc2 = 'Niveau: %u.' WHERE entry = 540;
UPDATE skyfire_string SET content_loc2 = 'Vie (base): %u. (max): %u. (actuelle): %u.' WHERE entry = 541;
UPDATE skyfire_string SET content_loc2 = 'Unit Flags: %u. Dynamique Flags: %u. Faction Template: %u.' WHERE entry = 542;
UPDATE skyfire_string SET content_loc2 = 'Butin: %u Pickpocket: %u Dépecage: %u' WHERE entry = 543;
UPDATE skyfire_string SET content_loc2 = 'Position: %f %f %f.' WHERE entry = 544;
UPDATE skyfire_string SET content_loc2 = '*** Est un marchand !' WHERE entry = 545;
UPDATE skyfire_string SET content_loc2 = '*** Est un entraineur !' WHERE entry = 546;
UPDATE skyfire_string SET content_loc2 = 'InstanceID: %u' WHERE entry = 547;
UPDATE skyfire_string SET content_loc2 = 'Joueur%s %s (guid: %u) Compte: %s (id: %u) Email: %s GMLevel: %u Derniere IP: %s Derniere connexion: %s Latence: %ums' WHERE entry = 548;
UPDATE skyfire_string SET content_loc2 = 'Race: %s Classe: %s Temps de jeu: %s Level: %u Argent: %ug%us%uc' WHERE entry = 549;
UPDATE skyfire_string SET content_loc2 = 'Temps de silence restant: %s, Temps de bannisement restant: %s' WHERE entry = 550;
UPDATE skyfire_string SET content_loc2 = '%s a désormais explore toutes les zones.' WHERE entry = 551;
UPDATE skyfire_string SET content_loc2 = '%s a encore des zones a explorer.' WHERE entry = 552;
UPDATE skyfire_string SET content_loc2 = '%s a explore toutes les zones pour vous.' WHERE entry = 553;
UPDATE skyfire_string SET content_loc2 = '%s a cache toutes les zones pour vous.' WHERE entry = 554;
UPDATE skyfire_string SET content_loc2 = 'Planer active' WHERE entry = 555;
UPDATE skyfire_string SET content_loc2 = 'Planer désactive' WHERE entry = 556;
UPDATE skyfire_string SET content_loc2 = '%s augmente votre niveau a (%i).' WHERE entry = 557;
UPDATE skyfire_string SET content_loc2 = '%s baisse votre niveau a (%i).' WHERE entry = 558;
UPDATE skyfire_string SET content_loc2 = '%s réinitialisé votre niveau de progression.' WHERE entry = 559;
UPDATE skyfire_string SET content_loc2 = 'Cette zone a été marquée comme explorée.' WHERE entry = 560;
UPDATE skyfire_string SET content_loc2 = 'Cette zone a été marquée comme non-explorée.' WHERE entry = 561;
UPDATE skyfire_string SET content_loc2 = 'GUID=%i mise a jour de l\'Index: %i, value: %i.' WHERE entry = 562;
UPDATE skyfire_string SET content_loc2 = 'Vous avez changé la valeur INSERT INTO Index %i de GUID=%i en %i.' WHERE entry = 563;
UPDATE skyfire_string SET content_loc2 = 'La valeur index %u est trop grande pour %u (nombre: %u).' WHERE entry = 564;
UPDATE skyfire_string SET content_loc2 = 'Modification uint32 %u: [OPCODE]: %u [VALEUR]: %u' WHERE entry = 565;
UPDATE skyfire_string SET content_loc2 = 'Vous modifiéz le champ %u: %u en un uint32: %u' WHERE entry = 566;
UPDATE skyfire_string SET content_loc2 = 'Modification float %u: [OPCODE]: %u [VALEUR]: %f' WHERE entry = 567;
UPDATE skyfire_string SET content_loc2 = 'Vous modifiéz le champ %u: %i en un float: %f' WHERE entry = 568;
UPDATE skyfire_string SET content_loc2 = 'Récupération uint32 %u: [OPCODE]: %u [VALEUR]: %u' WHERE entry = 569;
UPDATE skyfire_string SET content_loc2 = 'La valeur uint32 de %u dans %u est: %u' WHERE entry = 570;
UPDATE skyfire_string SET content_loc2 = 'Récupération float %u: [OPCODE]: %u [VALEUR]: %f' WHERE entry = 571;
UPDATE skyfire_string SET content_loc2 = 'La valeur float de %u dans %u est: %f' WHERE entry = 572;
UPDATE skyfire_string SET content_loc2 = '.SET 32Bit:[OPCODE]: %u [VALUE]: %u' WHERE entry = 573;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la valeur du champ: %u a la valeur: %u' WHERE entry = 574;
UPDATE skyfire_string SET content_loc2 = '.Mod32Value: [OPCODE]: %u [VALEUR]: %i' WHERE entry = 575;
UPDATE skyfire_string SET content_loc2 = 'Vous avez modifié la valeur du champ: %u a la valeur: %u' WHERE entry = 576;
UPDATE skyfire_string SET content_loc2 = 'Vous étés maintenant invisible.' WHERE entry = 577;
UPDATE skyfire_string SET content_loc2 = 'Vous étés maintenant visible.' WHERE entry = 578;
UPDATE skyfire_string SET content_loc2 = 'sélectionnéz un joueur ou une créature non ennemi.' WHERE entry = 579;
UPDATE skyfire_string SET content_loc2 = 'Le joueur %s a appris tous les sorts de race/classe par defaut et a complété toutes les quêtes recompensant des sorts.' WHERE entry = 580;
UPDATE skyfire_string SET content_loc2 = 'Objets trouvés a proximité (distance %f): %u' WHERE entry = 581;
UPDATE skyfire_string SET content_loc2 = 'Temps avant reapparition: Complet: %s Restant: %s' WHERE entry = 582;
UPDATE skyfire_string SET content_loc2 = '%d - |cffffffff|HgameÉvennement:%d|h[%s]|h|r%s' WHERE entry = 583;
UPDATE skyfire_string SET content_loc2 = 'Aucun Évennement trouvé !' WHERE entry = 584;
UPDATE skyfire_string SET content_loc2 = 'Évennement inexistant !' WHERE entry = 585;
UPDATE skyfire_string SET content_loc2 = 'Évennement %u: %s%s Debut: %s Fin: %s Occurrence: %s Duree:%s Prochain changement de phase: %s' WHERE entry = 586;

UPDATE skyfire_string SET content_loc2 = 'Évennement %u déja actif !' WHERE entry = 587;
UPDATE skyfire_string SET content_loc2 = 'Évennement %u inactif !' WHERE entry = 588;
UPDATE skyfire_string SET content_loc2 = 'Mouvement ponctuel (X: %f Y: %f Z: %f)' WHERE entry = 589;
UPDATE skyfire_string SET content_loc2 = 'Mouvement de peur' WHERE entry = 590;
UPDATE skyfire_string SET content_loc2 = 'Mouvement de distraction' WHERE entry = 591;
UPDATE skyfire_string SET content_loc2 = 'Vous avez appris toutes les recettes de metiers: %s' WHERE entry = 592;
UPDATE skyfire_string SET content_loc2 = 'Comptes actuellement bannis:' WHERE entry = 593;
UPDATE skyfire_string SET content_loc2 = '| Compte |DateBan |DateDéban |Banni par| Raison |' WHERE entry = 594;
UPDATE skyfire_string SET content_loc2 = 'IP actuellement bannies:' WHERE entry = 595;
UPDATE skyfire_string SET content_loc2 = '|IP |DateBan |DateDéban |Banni par| Raison |' WHERE entry = 596;
UPDATE skyfire_string SET content_loc2 = 'Maitres-du-jeu actuels:' WHERE entry = 597;
UPDATE skyfire_string SET content_loc2 = '| Compte | MJ |' WHERE entry = 598;
UPDATE skyfire_string SET content_loc2 = 'Aucun MJ.' WHERE entry = 599;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance gagne !' WHERE entry = 600;
UPDATE skyfire_string SET content_loc2 = 'La Horde gagne !' WHERE entry = 601;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le goulet des Chanteguerres commence dans 1 minute.' WHERE entry = 602;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le goulet des Chanteguerres commence dans 30 secondes. Preparez-vous !' WHERE entry = 603;
UPDATE skyfire_string SET content_loc2 = 'Que la bataille pour le goulet des Chanteguerres commence !' WHERE entry = 604;
UPDATE skyfire_string SET content_loc2 = '$n a capturé le drapeau de la Horde !' WHERE entry = 605;
UPDATE skyfire_string SET content_loc2 = '$n a capturé le drapeau de l\'Alliance !' WHERE entry = 606;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde a été lache par $n!' WHERE entry = 607;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été lache par $n !' WHERE entry = 608;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été ramené a sa base par $n !' WHERE entry = 609;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde a été ramené a sa base par $n !' WHERE entry = 610;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde a été ramassé par $n !' WHERE entry = 611;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été ramassé par $n !' WHERE entry = 612;
UPDATE skyfire_string SET content_loc2 = 'Les drapeaux sont maintenant places sur leur base.' WHERE entry = 613;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance est maintenant place sur sa base.' WHERE entry = 614;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde est maintenant place sur sa base.' WHERE entry = 615;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour l\'Oeil du Cyclone debute dans 1 minute.' WHERE entry = 636;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour l\'Oeil du Cyclone debute dans 30 secondes. Preparez-vous !' WHERE entry = 637;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour l\'Oeil du Cyclone debute !' WHERE entry = 638;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance' WHERE entry = 650;
UPDATE skyfire_string SET content_loc2 = 'La Horde' WHERE entry = 651;
UPDATE skyfire_string SET content_loc2 = 'Les ecuries' WHERE entry = 652;
UPDATE skyfire_string SET content_loc2 = 'La Forge' WHERE entry = 653;
UPDATE skyfire_string SET content_loc2 = 'La Ferme' WHERE entry = 654;
UPDATE skyfire_string SET content_loc2 = 'La Scierie' WHERE entry = 655;
UPDATE skyfire_string SET content_loc2 = 'La Mine' WHERE entry = 656;
UPDATE skyfire_string SET content_loc2 = '%s a pris %s' WHERE entry = 657;
UPDATE skyfire_string SET content_loc2 = '$n a défendu %s' WHERE entry = 658;
UPDATE skyfire_string SET content_loc2 = '$n a attaqué %s !' WHERE entry = 659;
UPDATE skyfire_string SET content_loc2 = '$n a attaque %s! Si rien n\'est fait, %s le contrôlera dans 1 minute!' WHERE entry = 660;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Bassin d\'Arathi commence dans 1 minute.' WHERE entry = 661;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Bassin d\'Arathi commence dans 30 secondes. Preparez-vous !' WHERE entry = 662;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Bassin d\'Arathi commence !' WHERE entry = 663;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a réunie $1776W unites de ressources, et est proche de la victoire !' WHERE entry = 664;
UPDATE skyfire_string SET content_loc2 = 'La Horde a réunie $1777W unites de ressources, et est proche de la victoire !' WHERE entry = 665;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris le contrôle de la Tour des mages !' WHERE entry = 667;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris le contrôle de la Tour des mages !' WHERE entry = 668;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris le contrôle des Ruines draenei !' WHERE entry = 669;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris le contrôle des Ruines draenei !' WHERE entry = 670;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris le contrôle de la Tour des elfes de sang !' WHERE entry = 671;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris le contrôle de la Tour des elfes de sang !' WHERE entry = 672;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris le contrôle des Ruines des saccageurs gangrenes !' WHERE entry = 673;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris le contrôle des Ruines des saccageurs gangrenes !' WHERE entry = 674;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu le contrôle de la Tour des mages !' WHERE entry = 675;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu le contrôle de la Tour des mages !' WHERE entry = 676;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu le contrôle des Ruines draenei !' WHERE entry = 677;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu le contrôle des Ruines draenei !' WHERE entry = 678;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu le contrôle de la Tour des elfes de sang !' WHERE entry = 679;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu le contrﾴle de la Tour des elfes de sang !' WHERE entry = 680;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu le contrôle des Ruines des saccageurs gangrenes !' WHERE entry = 681;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu le contrôle des Ruines des saccageurs gangrenes !' WHERE entry = 682;
UPDATE skyfire_string SET content_loc2 = '%s a pris le drapeau !' WHERE entry = 683;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le drapeau !' WHERE entry = 684;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le drapeau !' WHERE entry = 685;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau a été lache.' WHERE entry = 686;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau a été réinitialisé.' WHERE entry = 687;
UPDATE skyfire_string SET content_loc2 = 'Vous devez etre niveau %u pour former une equipe d\'arène.' WHERE entry = 700;
UPDATE skyfire_string SET content_loc2 = 'L\'arène ouvre ses portes dans 1 minute !' WHERE entry = 701;
UPDATE skyfire_string SET content_loc2 = 'L\'arène ouvre ses portes dans 30 secondes !' WHERE entry = 702;
UPDATE skyfire_string SET content_loc2 = 'L\'arène ouvre ses portes dans 15 secondes !' WHERE entry = 703;
UPDATE skyfire_string SET content_loc2 = 'Le match a debute !' WHERE entry = 704;
UPDATE skyfire_string SET content_loc2 = 'Vous devez attendre %s avant de retrouvér la parole.' WHERE entry = 705;
UPDATE skyfire_string SET content_loc2 = 'Les Équipements suivant ont des problemes avec leur stockage dans l\'inventaire.' WHERE entry = 706;
UPDATE skyfire_string SET content_loc2 = '%s ne souhaite pas etre derange et ne peut pas recevoir de chuchotements: %s' WHERE entry = 707;
UPDATE skyfire_string SET content_loc2 = '%s est absent: %s' WHERE entry = 708;
UPDATE skyfire_string SET content_loc2 = 'Ne pas deranger' WHERE entry = 709;
UPDATE skyfire_string SET content_loc2 = 'Absent' WHERE entry = 710;
UPDATE skyfire_string SET content_loc2 = 'Statut de la file d''attente pour %s (Lvl: %u a %u) File d''attente de l''Alliance: %u (requiert encore %u) File d''attente de la Horde: %u (requiert encore %u)' WHERE entry = 711;


UPDATE skyfire_string SET content_loc2 = '|cffff0000[Annonce File d\'attente CB]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r' WHERE entry = 712;
UPDATE skyfire_string SET content_loc2 = 'Vous devez etre niveau %u pour rejoindre une equipe d\'arène !' WHERE entry = 713;
UPDATE skyfire_string SET content_loc2 = 'Vous ne remplissez pas les exigences de niveau de ce champ de bataille.' WHERE entry = 715;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Annonce File d\'attente CB]:|r %s -- [%u-%u] Cela debute !|r' WHERE entry = 717;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Annonce file d\'attente d\'arène]:|r Toutes les arènes -- Entree : %ux%u : %u|r' WHERE entry = 718;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Annonce file d\'attente d\'arène]:|r Toutes les arènes -- Sortie : %ux%u : %u|r' WHERE entry = 719;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe est trop grand pour ce champ de bataille. Veuillez regrouper pour rejoindre.' WHERE entry = 720;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe est trop grand pour cette arène. Veuillez regrouper pour rejoindre.' WHERE entry = 721;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe comporte des membres n\'appartenant pas a votre equipe d\'arène. Veuillez regrouper pour rejoindre.' WHERE entry = 722;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe ne comporte pas assez de joueurs pour rejoindre ce match.' WHERE entry = 723;
UPDATE skyfire_string SET content_loc2 = 'L\'equipe Jaune l\'emporte !' WHERE entry = 724;
UPDATE skyfire_string SET content_loc2 = 'L\'equipe Verte l\'emporte !' WHERE entry = 725;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a pas assez de joueurs sur ce champ de bataille. Il prendra bientot fin, a moins que des joueurs le rejoigne afin d\'equilibrer la balance.' WHERE entry = 726;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe comporte un membre hors ligne. Veuillez le supprimér avant de rejoindre.' WHERE entry = 727;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe contient des joueurs d\'une faction opposee. Vous ne pouvez pas rejoindre ce champ de bataille comme un groupe.' WHERE entry = 728;
UPDATE skyfire_string SET content_loc2 = 'Votre groupe comporte des joueurs de differentes tranches de niveau. Vous ne pouvez pas rejoindre comme un groupe.' WHERE entry = 729;
UPDATE skyfire_string SET content_loc2 = 'Un membre de votre groupe est déja inscrit pour ce champ de bataille. Il doit le quitter avant que vous puissiez rejoindre ce champ de bataille comme un groupe.' WHERE entry = 730;
UPDATE skyfire_string SET content_loc2 = 'Un membre de votre groupe est un deserteur. Vous ne pouvez pas rejoindre comme un groupe.' WHERE entry = 731;
UPDATE skyfire_string SET content_loc2 = 'Un membre de votre groupe est déja inscrit pour trois champ de bataille. Vous ne pouvez pas rejoindre comme un groupe.' WHERE entry = 732;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas téléporter sur une carte de champ de bataille ou d\'arène.' WHERE entry = 733;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas invoquer un joueur sur une carte de champ de bataille ou d\'arène.' WHERE entry = 734;
UPDATE skyfire_string SET content_loc2 = 'Vous devez etre en mode MJ afin de téléporter un joueur dans sur un champ de bataille.' WHERE entry = 735;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas vous téléporter d\'un champ de bataille a un autre. Veuillez d\'abord quitter le champ de bataille actuel.' WHERE entry = 736;
UPDATE skyfire_string SET content_loc2 = 'Les arènes sont configurees en mode 1c1 pour debogage. Vous ne pouvez donc pas rejoindre comme un groupe.' WHERE entry = 737;
UPDATE skyfire_string SET content_loc2 = 'Les arènes sont configurees avec le quota normal de joueurs.' WHERE entry = 738;
UPDATE skyfire_string SET content_loc2 = 'Les champs de bataille sont configures en mode 1c0 pour debogage.' WHERE entry = 739;
UPDATE skyfire_string SET content_loc2 = 'Les champs de bataille sont configures avec le quota normal de joueurs.' WHERE entry = 740;
UPDATE skyfire_string SET content_loc2 = 'Mise a jour des points d\'arène en fonction des statistiques des equipes. Cela peut prendre plusieurs minutes. Veuillez patienter...' WHERE entry = 741;
UPDATE skyfire_string SET content_loc2 = 'Distribution des points d\'arènes aux joueurs...' WHERE entry = 742;
UPDATE skyfire_string SET content_loc2 = 'Fin de configuration des points d\'arène pour les joueurs connectés.' WHERE entry = 743;
UPDATE skyfire_string SET content_loc2 = 'Modification du quota de joueurs, des points d\'arène etc. pour les equipes d\'arène chargees. Envoi des nouvelles statistiques aux joueurs connectés...' WHERE entry = 744;
UPDATE skyfire_string SET content_loc2 = 'Modification effectuee.' WHERE entry = 745;
UPDATE skyfire_string SET content_loc2 = 'Mise a jour des points d\'arène effectuee.' WHERE entry = 746;
UPDATE skyfire_string SET content_loc2 = 'Pas assez de joueurs. La partie se termine dans %u min.' WHERE entry = 750;
UPDATE skyfire_string SET content_loc2 = 'Pas assez de joueurs. La partie se termine dans %u sec.' WHERE entry = 751;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Goulet des Chanteguerres commence dans 2 minutes.' WHERE entry = 753;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Bassin d\'Arathi commence dans 2 minutes.' WHERE entry = 754;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour l\'Oeil du Cyclone commence dans 2 minutes.' WHERE entry = 755;
UPDATE skyfire_string SET content_loc2 = 'Titre choisie pour le joueur %s remis a non connu.' WHERE entry = 356;
UPDATE skyfire_string SET content_loc2 = 'Titre %u (%s) déterminé pour le titre choisir du joueur %s.' WHERE entry = 355;
UPDATE skyfire_string SET content_loc2 = 'Titre %u (%s) enlevé de la listes des titres connu du joueur%s.' WHERE entry = 354;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 350;
UPDATE skyfire_string SET content_loc2 = 'Aucun titres trouvés!' WHERE entry = 351;
UPDATE skyfire_string SET content_loc2 = 'Id de titre invalide: %u' WHERE entry = 352;
UPDATE skyfire_string SET content_loc2 = 'Titre %u (%s) ajouté dans la liste de titres connu du joueur %s.' WHERE entry = 353;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 349;
UPDATE skyfire_string SET content_loc2 = 'Arena testing turned %s' WHERE entry = 785;
UPDATE skyfire_string SET content_loc2 = '|cffff0000[Automatique]:|r' WHERE entry = 786;
UPDATE skyfire_string SET content_loc2 = '|cffffff00[|c1f40af20Message de|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry = 787;
UPDATE skyfire_string SET content_loc2 = 'Nom Invalide' WHERE entry = 800;
UPDATE skyfire_string SET content_loc2 = 'Vous ne possèdez pas assez d\'argent' WHERE entry = 801;
UPDATE skyfire_string SET content_loc2 = 'Vous ne possèdez pas assez d\'emplacements libres dans votre inventaire' WHERE entry = 802;
UPDATE skyfire_string SET content_loc2 = 'Votre partenaire ne possède pas assez d\'emplacements libres dans son inventaire' WHERE entry = 803;
UPDATE skyfire_string SET content_loc2 = 'Vous n\'avez pas la permission d\'executer cette fonction' WHERE entry = 804;
UPDATE skyfire_string SET content_loc2 = 'Langue inconnue' WHERE entry = 805;
UPDATE skyfire_string SET content_loc2 = 'Vous ne connaissez pas cette langue' WHERE entry = 806;
UPDATE skyfire_string SET content_loc2 = 'Veuillez fournir un nom de personnage' WHERE entry = 807;
UPDATE skyfire_string SET content_loc2 = 'Joueur %s introuvable ou hors ligne' WHERE entry = 808;
UPDATE skyfire_string SET content_loc2 = 'Compte du personnage %s introuvable' WHERE entry = 809;
UPDATE skyfire_string SET content_loc2 = '|Hplayer:$N|h[$N]|h a accompli le haut fait $a !' WHERE entry = 810;
UPDATE skyfire_string SET content_loc2 = 'Maitre de guilde' WHERE entry = 811;
UPDATE skyfire_string SET content_loc2 = 'Officier' WHERE entry = 812;
UPDATE skyfire_string SET content_loc2 = 'Vétéran' WHERE entry = 813;
UPDATE skyfire_string SET content_loc2 = 'Membre' WHERE entry = 814;
UPDATE skyfire_string SET content_loc2 = 'Initie' WHERE entry = 815;
UPDATE skyfire_string SET content_loc2 = 'Attention: vous avez rejoint une zone ou le vol est interdite et vous allez etre desarconne.' WHERE entry = 816;
UPDATE skyfire_string SET content_loc2 = 'Arret du demon...' WHERE entry = 1000;
UPDATE skyfire_string SET content_loc2 = 'Compte supprimé: %s' WHERE entry = 1001;
UPDATE skyfire_string SET content_loc2 = 'Compte %s NON supprimé (le format du fichier SQL a probablement été mis a jour).' WHERE entry = 1002;
UPDATE skyfire_string SET content_loc2 = 'Compte %s NON supprimé (erreur inconnue)' WHERE entry = 1003;
UPDATE skyfire_string SET content_loc2 = 'Compte cree: %s' WHERE entry = 1004;
UPDATE skyfire_string SET content_loc2 = 'Le nom de compte ne peut pas depasser 16 caracteres (limite du client). Compte NON cree !' WHERE entry = 1005;
UPDATE skyfire_string SET content_loc2 = 'Ce nom de compte existe déja !' WHERE entry = 1006;
UPDATE skyfire_string SET content_loc2 = 'Compte %s NON cree (le format du fichier SQL a probablement été mis a jour)' WHERE entry = 1007;
UPDATE skyfire_string SET content_loc2 = 'Compte %s NON cree (erreur inconnue)' WHERE entry = 1008;
UPDATE skyfire_string SET content_loc2 = 'Joueur %s (Guid: %u) du compte %s (Id: %u) supprimé.' WHERE entry = 1009;
UPDATE skyfire_string SET content_loc2 = '-==================================================================-' WHERE entry = 1012;
UPDATE skyfire_string SET content_loc2 = '|<Erreur> | %20s |<Erreur>|<Er>| <Erreur> |' WHERE entry = 1011;
UPDATE skyfire_string SET content_loc2 = '-[Compte][Personnage][ IP][Map][Zone][Exp][GMLev]-' WHERE entry = 1010;
UPDATE skyfire_string SET content_loc2 = 'Aucun joueur en ligne.' WHERE entry = 1014;
UPDATE skyfire_string SET content_loc2 = 'Compte %s (Id: %u) a désormais la permission d\'utiliser l\'expansion %u.' WHERE entry = 1100;
UPDATE skyfire_string SET content_loc2 = 'Message du jour changé en: %s' WHERE entry = 1101;
UPDATE skyfire_string SET content_loc2 = 'Message envoye a %s: %s' WHERE entry = 1102;
UPDATE skyfire_string SET content_loc2 = '%d - %s %s' WHERE entry = 1103;
UPDATE skyfire_string SET content_loc2 = '%d - %s' WHERE entry = 1104;
UPDATE skyfire_string SET content_loc2 = '%d - %s' WHERE entry = 1105;
UPDATE skyfire_string SET content_loc2 = '%d - %s %s' WHERE entry = 1106;
UPDATE skyfire_string SET content_loc2 = '%d - %s' WHERE entry = 1107;
UPDATE skyfire_string SET content_loc2 = '%d - %s %s' WHERE entry = 1108;
UPDATE skyfire_string SET content_loc2 = '%d - %s %s %s %s' WHERE entry = 1109;
UPDATE skyfire_string SET content_loc2 = '%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry = 1110;
UPDATE skyfire_string SET content_loc2 = '%d - %s X:%f Y:%f Z:%f MapId:%d' WHERE entry = 1111;
UPDATE skyfire_string SET content_loc2 = 'Erreur lors de l\'ouverture du fichier: %s' WHERE entry = 1112;
UPDATE skyfire_string SET content_loc2 = 'Le compte %s (%u) a atteint la limite de personnages autorisés (limite du client)' WHERE entry = 1113;
UPDATE skyfire_string SET content_loc2 = 'Le fichier exporte comporte des champs défaillants !' WHERE entry = 1114;
UPDATE skyfire_string SET content_loc2 = 'Nom de personnage invalide !' WHERE entry = 1115;
UPDATE skyfire_string SET content_loc2 = 'GUID de personnage invalide !' WHERE entry = 1116;
UPDATE skyfire_string SET content_loc2 = 'Personnage de GUID %u en action !' WHERE entry = 1117;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 1118;
UPDATE skyfire_string SET content_loc2 = 'Vous devez utiliser male ou female comme sexe.' WHERE entry = 1119;
UPDATE skyfire_string SET content_loc2 = 'Vous changez le sexe de %s en %s.' WHERE entry = 1120;
UPDATE skyfire_string SET content_loc2 = 'Votre sexe a été changé en %s par %s.' WHERE entry = 1121;
UPDATE skyfire_string SET content_loc2 = '(%u/%u +perm %u +temp %u)' WHERE entry = 1122;
UPDATE skyfire_string SET content_loc2 = 'Familier introuvable.' WHERE entry = 1123;
UPDATE skyfire_string SET content_loc2 = 'Type de familier invalide.' WHERE entry = 1124;
UPDATE skyfire_string SET content_loc2 = 'Votre familier a appris tous ses talents.' WHERE entry = 1125;
UPDATE skyfire_string SET content_loc2 = 'Les talents de votre familier ont été réinitialisés.' WHERE entry = 1126;
UPDATE skyfire_string SET content_loc2 = 'Les talents du familier de %s ont été réinitialisés.' WHERE entry = 1127;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 1128;
UPDATE skyfire_string SET content_loc2 = '%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry = 1129;
UPDATE skyfire_string SET content_loc2 = 'Vous essayez de visionner une cinematique inexistante.' WHERE entry = 1200;
UPDATE skyfire_string SET content_loc2 = 'Vous essayez de visionner une video inexistante.' WHERE entry = 1201;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance' WHERE entry = 1300;
UPDATE skyfire_string SET content_loc2 = 'La Horde' WHERE entry = 1301;
UPDATE skyfire_string SET content_loc2 = '%s a été détruit par %s!' WHERE entry = 1302;
UPDATE skyfire_string SET content_loc2 = '%s est attaque! Si rien n \'est fait, %s va le detruire!' WHERE entry = 1303;
UPDATE skyfire_string SET content_loc2 = '%s a été pris par %s!' WHERE entry = 1304;
UPDATE skyfire_string SET content_loc2 = '%s a été pris par %s!' WHERE entry = 1305;
UPDATE skyfire_string SET content_loc2 = '%s a été pris par %s!' WHERE entry = 1306;
UPDATE skyfire_string SET content_loc2 = '%s est attaque! Si rien n\'est fait, %s va le detruire!' WHERE entry = 1307;
UPDATE skyfire_string SET content_loc2 = '%s a pris %s! Ces fournitures serviront pour le renforcement des troupes!' WHERE entry = 1308;
UPDATE skyfire_string SET content_loc2 = 'Mine de Gouffrefer' WHERE entry = 1309;
UPDATE skyfire_string SET content_loc2 = 'Mine de Froide-Dent' WHERE entry = 1310;
UPDATE skyfire_string SET content_loc2 = 'Station de secours Foudrepique' WHERE entry = 1311;
UPDATE skyfire_string SET content_loc2 = 'Bunker sud de Dun Baldar' WHERE entry = 1312;
UPDATE skyfire_string SET content_loc2 = 'Bunker nord de Dun Baldar' WHERE entry = 1313;
UPDATE skyfire_string SET content_loc2 = 'cimetière Foudrepique' WHERE entry = 1314;
UPDATE skyfire_string SET content_loc2 = 'Bunker de l\'Aile de Glace' WHERE entry = 1315;
UPDATE skyfire_string SET content_loc2 = 'cimetière de Gatepierre' WHERE entry = 1316;
UPDATE skyfire_string SET content_loc2 = 'Bunker de Gatepierre' WHERE entry = 1317;
UPDATE skyfire_string SET content_loc2 = 'cimetière de Tombeneige' WHERE entry = 1318;
UPDATE skyfire_string SET content_loc2 = 'Tour de Glace-sang' WHERE entry = 1319;
UPDATE skyfire_string SET content_loc2 = 'cimetière de Glace-sang' WHERE entry = 1320;
UPDATE skyfire_string SET content_loc2 = 'Tour de la Halte' WHERE entry = 1321;
UPDATE skyfire_string SET content_loc2 = 'cimetière Loup-de-Givre' WHERE entry = 1322;
UPDATE skyfire_string SET content_loc2 = 'Tour Est Loup-de-Givre' WHERE entry = 1323;
UPDATE skyfire_string SET content_loc2 = 'Tour Ouest Loup-de-Givre' WHERE entry = 1324;
UPDATE skyfire_string SET content_loc2 = 'Hutte du Clan Loup-de-Givre' WHERE entry = 1325;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour la Vallee d\'Alterac commence dans 1 minute.' WHERE entry = 1326;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour la Vallee d\'Alterac commence dans 30 secondes. Preparez-vous!' WHERE entry = 1327;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour la Vallee d\'Alterac commence!' WHERE entry = 1328;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance est bientot a court de fournitures!' WHERE entry = 1329;
UPDATE skyfire_string SET content_loc2 = 'La Horde est bientot a court de fournitures!' WHERE entry = 1330;
UPDATE skyfire_string SET content_loc2 = 'Le General du Clan Loup-de-Givre est Mort!' WHERE entry = 1331;
UPDATE skyfire_string SET content_loc2 = 'Le General du Clan Fourdrepique est Mort!' WHERE entry = 1332;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour la Vallee d\'Alterac commence dans 2 minutes.' WHERE entry = 1333;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Nouvelle requête de la part de|r|cffff00ff %s.|r |cff00ff00Requête n' WHERE entry = 2000;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Le personnage|r|cffff00ff %s |r|cff00ff00a edite sa requête n' WHERE entry = 2001;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Le personnage|r|cffff00ff %s |r|cff00ff00a abandonne la requête n' WHERE entry = 2002;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Ferme par|r:|cff00ccff %s|r' WHERE entry = 2003;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00efface par|r:|cff00ccff %s|r' WHERE entry = 2004;
UPDATE skyfire_string SET content_loc2 = 'Requête non-trouvée.' WHERE entry = 2005;
UPDATE skyfire_string SET content_loc2 = 'Merci de fermer la requête avant de la supprimér definitvement.' WHERE entry = 2006;
UPDATE skyfire_string SET content_loc2 = 'La requête %d est déja assignee.' WHERE entry = 2007;
UPDATE skyfire_string SET content_loc2 = '%u requêtes rechargees avec succès a partir de la base de donnée.' WHERE entry = 2008;
UPDATE skyfire_string SET content_loc2 = 'Affichage de la liste des requêtes ouvertes.' WHERE entry = 2009;
UPDATE skyfire_string SET content_loc2 = 'Affichage de la liste des requêtes ouvertes dont le createur est en ligne.' WHERE entry = 2010;
UPDATE skyfire_string SET content_loc2 = 'Affichage de la liste des requêtes fermees.' WHERE entry = 2011;
UPDATE skyfire_string SET content_loc2 = 'Nom invalide specifie. Le nom devrait etre celui d\'un Maitre de Jeu en ligne.' WHERE entry = 2012;
UPDATE skyfire_string SET content_loc2 = 'Cette requête vous est déja assignee. Pour la desassigner, merci d\'utiliser .ticket unassign %d et de la reassigner.' WHERE entry = 2013;
UPDATE skyfire_string SET content_loc2 = 'La requête %d n\'est pas assignee, vous ne pouvez pas la desassigner.' WHERE entry = 2014;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez desassigner des requêtes venant de membres du staff avec un niveau de securite superieur au votre.' WHERE entry = 2015;
UPDATE skyfire_string SET content_loc2 = 'Ne peut fermer la requête %d, c\'est assigne a un autre MJ.' WHERE entry = 2016;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Commentaire de MJ|r: [%s]|r' WHERE entry = 2023;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Cree par|r:|cff00ccff %s|r' WHERE entry = 2018;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Derniere modification|r:|cff00ccff il y\'a %s|r' WHERE entry = 2019;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Assigne a|r:|cff00ccff %s|r' WHERE entry = 2020;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Desassigne par|r:|cff00ccff %s|r ' WHERE entry = 2021;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Message de requête|r: [%s]|r' WHERE entry = 2022;
UPDATE skyfire_string SET content_loc2 = '|cffaaffaaRequête|r:|cffaaccff %d.|r' WHERE entry = 2017;
UPDATE skyfire_string SET content_loc2 = '|cff00ff00Cree|r:|cff00ccff il y\'a %s|r ' WHERE entry = 2025;
UPDATE skyfire_string SET content_loc2 = 'Vous avez gele le joueur %s' WHERE entry = 5000;
UPDATE skyfire_string SET content_loc2 = 'ca aurait pu etre marrant mais non... Vous ne pouvez pas vous geler vous-meme!' WHERE entry = 5001;
UPDATE skyfire_string SET content_loc2 = 'Entree invalide, verifier le nom de la cible.' WHERE entry = 5002;
UPDATE skyfire_string SET content_loc2 = 'Vous avez degele le joueur %s.' WHERE entry = 5003;
UPDATE skyfire_string SET content_loc2 = 'Il n\'y a pas de joueurs geles.' WHERE entry = 5004;
UPDATE skyfire_string SET content_loc2 = 'Les joueurs suivants sont geles sur le serveur:' WHERE entry = 5005;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 5006;
UPDATE skyfire_string SET content_loc2 = 'Vous devez etre dans un groupe de raid pour acceder a cette instance.' WHERE entry = 5007;
UPDATE skyfire_string SET content_loc2 = 'Le son %u est joue sur le serveur' WHERE entry = 5009;
UPDATE skyfire_string SET content_loc2 = 'linkGUID: %u, Entree: %u (%s)' WHERE entry = 5010;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez vous téléporter sur vous-meme!' WHERE entry = 5011;
UPDATE skyfire_string SET content_loc2 = 'Aucunes cartes trouvées!' WHERE entry = 5012;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 5013;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 5014;
UPDATE skyfire_string SET content_loc2 = '[Champ de Bataille]' WHERE entry = 5015;
UPDATE skyfire_string SET content_loc2 = '[arène]' WHERE entry = 5016;
UPDATE skyfire_string SET content_loc2 = '[ReSET du compteur Raid: %s]' WHERE entry = 5017;
UPDATE skyfire_string SET content_loc2 = '[Compteur de reSET d\'Instance Heroique: %s]' WHERE entry = 5018;
UPDATE skyfire_string SET content_loc2 = '[Monture utilisable]' WHERE entry = 5019;
UPDATE skyfire_string SET content_loc2 = '|cfff00000[Annonce MJ]: %s|r' WHERE entry = 6613;
UPDATE skyfire_string SET content_loc2 = 'Notification aux MJ\'s - ' WHERE entry = 6614;
UPDATE skyfire_string SET content_loc2 = '|cffffff00[|c1f40af20Annonce de GM par|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry = 6615;
UPDATE skyfire_string SET content_loc2 = 'Le Silence est ON pour %s' WHERE entry = 6616;
UPDATE skyfire_string SET content_loc2 = 'WORLD: Refuse les connections.' WHERE entry = 7523;
UPDATE skyfire_string SET content_loc2 = 'WORLD: Accepte les connections.' WHERE entry = 7524;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris Le Surplomb!' WHERE entry = 10001;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris Le Surplomb!' WHERE entry = 10002;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris Le Stade!' WHERE entry = 10003;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris Le Stade!' WHERE entry = 10004;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris La Colline Brisee!' WHERE entry = 10005;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris La Colline Brisee!' WHERE entry = 10006;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu Le Surplomb!' WHERE entry = 10007;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu Le Surplomb!' WHERE entry = 10008;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu Le Stade!' WHERE entry = 10009;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu Le Stade!' WHERE entry = 10010;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu La Colline Brisee!' WHERE entry = 10011;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu La Colline Brisee!' WHERE entry = 10012;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Balise de l\'Ouest!' WHERE entry = 10013;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Balise de l\'Ouest!' WHERE entry = 10014;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Balise de l\'Est!' WHERE entry = 10015;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Balise de l\'Est!' WHERE entry = 10016;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le cimetière des Fleches Jumelles!' WHERE entry = 10017;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le cimetière des Fleches Jumelles!' WHERE entry = 10018;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Balise de l\'Ouest!' WHERE entry = 10019;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Balise de l\'Ouest!' WHERE entry = 10020;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Balise de l\'Est!' WHERE entry = 10021;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Balise de l\'Est!' WHERE entry = 10022;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu le cimetière des Fleches Jumelles!' WHERE entry = 10023;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu le cimetière des Fleches Jumelles!' WHERE entry = 10024;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé Halaa!' WHERE entry = 10025;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé Halaa!' WHERE entry = 10026;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu Halaa!' WHERE entry = 10027;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu Halaa!' WHERE entry = 10028;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris une Tour de l\'Esprit!' WHERE entry = 10029;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris une Tour de l\'Esprit!' WHERE entry = 10030;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu une Tour de l\'Esprit!' WHERE entry = 10031;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu une Tour de l\'Esprit!' WHERE entry = 10032;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Tour du Passage du Nord!' WHERE entry = 10033;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Tour du Passage du Nord!' WHERE entry = 10034;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Tour de Mur de l\'Est!' WHERE entry = 10035;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Tour de Mur de l\'Est!' WHERE entry = 10036;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Tour de Garde de la Couronne!' WHERE entry = 10037;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Tour de Garde de la Couronne!' WHERE entry = 10038;
UPDATE skyfire_string SET content_loc2 = 'La Horde a pris la Tour de Pestebois!' WHERE entry = 10039;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a pris la Tour de Pestebois!' WHERE entry = 10040;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Tour du Passage du Nord!' WHERE entry = 10041;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Tour du Passage du Nord!' WHERE entry = 10042;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Tour de Mur de l\'Est!' WHERE entry = 10043;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Tour de Mur de l\'Est!' WHERE entry = 10044;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Tour de Garde de la Couronne!' WHERE entry = 10045;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Tour de Garde de la Couronne!' WHERE entry = 10046;
UPDATE skyfire_string SET content_loc2 = 'La Horde a perdu la Tour de Pestebois!' WHERE entry = 10047;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a perdu la Tour de Pestebois!' WHERE entry = 10048;
UPDATE skyfire_string SET content_loc2 = 'La Horde a collecte 200 Silithiste!' WHERE entry = 10049;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a collecte 200 Silithiste!' WHERE entry = 10050;
UPDATE skyfire_string SET content_loc2 = 'Amenez-moi jusqu\'a la Tour de Passage du Nord.' WHERE entry = 10051;
UPDATE skyfire_string SET content_loc2 = 'Amenez-moi jusqu\'a la Tour du Mur de l\'Est.' WHERE entry = 10052;
UPDATE skyfire_string SET content_loc2 = 'Amenez-moi jusqu\'a la Tour de Garde de la Couronne.' WHERE entry = 10053;
UPDATE skyfire_string SET content_loc2 = 'Donnez-moi le drapeau, je l\'emmenerais a la balise centrale pour la gloire de l\'Alliance!' WHERE entry = 10054;
UPDATE skyfire_string SET content_loc2 = 'Donnez-moi le drapeau, je l\'emmenerais a la balise centrale pour la gloire de la Horde!' WHERE entry = 10055;
UPDATE skyfire_string SET content_loc2 = '|cffffff00[|c00077766Annonce Automatique|cffffff00]: |cFFF222FF%s|r' WHERE entry = 11000;
UPDATE skyfire_string SET content_loc2 = 'Vous n\'avez pas choisi -1 ou le realmID courant ou vous étés.' WHERE entry = 11001;
UPDATE skyfire_string SET content_loc2 = 'Masque de phasing: %u' WHERE entry = 5020;
UPDATE skyfire_string SET content_loc2 = 'Armure: %u' WHERE entry = 5021;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le Portail des Titans!' WHERE entry = 10063;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le Portail des Titans!' WHERE entry = 10064;
UPDATE skyfire_string SET content_loc2 = '%s a été détruit!' WHERE entry = 10061;
UPDATE skyfire_string SET content_loc2 = 'Round 1 - fini!' WHERE entry = 10062;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Rivage des Anciens commence!' WHERE entry = 10059;
UPDATE skyfire_string SET content_loc2 = '%s est en train d\'etre attaque!' WHERE entry = 10060;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Rivage des Anciens commence dans 30 secondes. Preparez-vous!' WHERE entry = 10058;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Rivage des Anciens commence dans 2 minutes.' WHERE entry = 10056;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour le Rivage des Anciens commence dans 1 minute.' WHERE entry = 10057;
UPDATE skyfire_string SET content_loc2 = 'Donne le contrôle a la premiere personne qui joint le canal "%s": Active.' WHERE entry = 5022;
UPDATE skyfire_string SET content_loc2 = 'L\'instance est fermee.' WHERE entry = 5008;
UPDATE skyfire_string SET content_loc2 = 'Entree: %u' WHERE entry = 5024;
UPDATE skyfire_string SET content_loc2 = 'Type: %u' WHERE entry = 5025;
UPDATE skyfire_string SET content_loc2 = 'DisplayID: %u' WHERE entry = 5026;
UPDATE skyfire_string SET content_loc2 = 'Nom: %s' WHERE entry = 5027;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas parler, crier ou faire des emotes tant que vous n\'avez pas le level %d.' WHERE entry = 6604;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas chuchoter tant que vous n\'avez pas le level %d.' WHERE entry = 6605;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas ecrire sur les canaux tant que vous n\'avez pas le level %d.' WHERE entry = 6606;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas utiliser l\'hotel des ventes tant que vous n\'avez pas le level %d.' WHERE entry = 6607;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas ecrire des requêtes tant que vous n\'avez pas le level %d.' WHERE entry = 6608;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas effectuer d\'echangés tant que vous n\'avez pas le level %d.' WHERE entry = 6609;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas echangér avec des personnages ayant un level plus bas que %d.' WHERE entry = 6610;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas envoyer de mails tant que vous n\'avez pas le level %d.' WHERE entry = 6611;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez pas envoyer de mails avec des personnages ayant un level plus bas que %d.' WHERE entry = 6612;
UPDATE skyfire_string SET content_loc2 = '|cff00ccff%s|r |cff00ff00A ajoute le commentaire|r: [%s]|r' WHERE entry = 2024;
UPDATE skyfire_string SET content_loc2 = '-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' WHERE entry = 1013;
UPDATE skyfire_string SET content_loc2 = '-======================== Joueurs en Ligne =======================-' WHERE entry = 1015;
UPDATE skyfire_string SET content_loc2 = 'Ce champ de guerre a été désactivé . Vous ne pouvez ГЄtre en liste d\'attente.' WHERE entry = 747;
UPDATE skyfire_string SET content_loc2 = 'Les arènes sont désactivée . Vous ne pouvez les rejoindres.' WHERE entry = 748;
UPDATE skyfire_string SET content_loc2 = 'Item \'%u\' (avec extended cost %u) est déja dans la liste du vendeur.' WHERE entry = 210;
UPDATE skyfire_string SET content_loc2 = 'L\'entree %u n\'a pas été trouvée dans la table créature_template.' WHERE entry = 817;
UPDATE skyfire_string SET content_loc2 = 'L\'entree %u n\'a pas été trouvée dans sCréatureStorage. Il est possible que ce soit une nouvelle ligne inseree dans créature_template, mais vous ne pouvez pas ajouter d\'autres créatures sans redemarrer le serveur. Seule la modification est permise.' WHERE entry = 818;
UPDATE skyfire_string SET content_loc2 = 'Le Round 2 de la bataille du Rivage des Anciens commence dans 1 minute.' WHERE entry = 10065;
UPDATE skyfire_string SET content_loc2 = 'Le Round 2 commence dans 30 secondes. Preparez-vous!' WHERE entry = 10066;
UPDATE skyfire_string SET content_loc2 = 'La chambre a été ouverte! La Relique des Titans est vulnerable!' WHERE entry = 10067;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le cimetière Sud!' WHERE entry = 10068;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le cimetière Ouest!' WHERE entry = 10069;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a capturé le cimetière Est!' WHERE entry = 10070;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le cimetière Sud!' WHERE entry = 10071;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le cimetière Ouest!' WHERE entry = 10072;
UPDATE skyfire_string SET content_loc2 = 'La Horde a capturé le cimetière Est!' WHERE entry = 10073;
UPDATE skyfire_string SET content_loc2 = 'Un ou plusieur paramètres ont des valeurs incorrectes .' WHERE entry = 62;
UPDATE skyfire_string SET content_loc2 = '| GUID | Nom| Compte | Date d\'Effacement|' WHERE entry = 1016;
UPDATE skyfire_string SET content_loc2 = '| %10u | %20s | %15s (%10u) | %19s |' WHERE entry = 1017;
UPDATE skyfire_string SET content_loc2 = '==========================================================================================' WHERE entry = 1018;
UPDATE skyfire_string SET content_loc2 = 'Pas de joueurs trouvés.' WHERE entry = 1019;
UPDATE skyfire_string SET content_loc2 = 'Restauration des joueurs suivants:' WHERE entry = 1020;
UPDATE skyfire_string SET content_loc2 = 'Effacement des joueurs suivants:' WHERE entry = 1021;
UPDATE skyfire_string SET content_loc2 = 'ERREUR: Vous pouvez assigner un nouveau nom seulement si vous avez sélectionné un personnage seul!' WHERE entry = 1022;
UPDATE skyfire_string SET content_loc2 = 'Le personnage \'%s\' (GUID: %u Compte %u) ne peut pas etre restaure: le compte n\'existe pas!' WHERE entry = 1023;
UPDATE skyfire_string SET content_loc2 = 'Le personnage \'%s\' (GUID: %u Compte %u) ne peut pas etre restaure: la liste de personnages est pleine!' WHERE entry = 1024;
UPDATE skyfire_string SET content_loc2 = 'Le personnage \'%s\' (GUID: %u Compte %u) ne peut pas etre restaure: le nom specifie est déja en cours d\'utilisation!' WHERE entry = 1025;
UPDATE skyfire_string SET content_loc2 = 'GUID: %u Nom: %s Compte: %s (%u) Date: %s' WHERE entry = 1026;
UPDATE skyfire_string SET content_loc2 = 'Id-Butin: %u' WHERE entry = 5028;
UPDATE skyfire_string SET content_loc2 = 'Impossible de supprimé le personnage, interrompue.' WHERE entry = 1130;
UPDATE skyfire_string SET content_loc2 = 'Resultat a atteint la limite (resultats max: %d)' WHERE entry = 5029;
UPDATE skyfire_string SET content_loc2 = 'The following characters match your query:' WHERE entry = 1131;
UPDATE skyfire_string SET content_loc2 = 'Personnages actuellement Banni:' WHERE entry = 1132;
UPDATE skyfire_string SET content_loc2 = '|Joueurs|DateBan |DateDéban | Banni par |Ban Raison |' WHERE entry = 1133;
UPDATE skyfire_string SET content_loc2 = 'Cite' WHERE entry = 819;
UPDATE skyfire_string SET content_loc2 = 'La bataille va commencer dans 2 minutes.' WHERE entry = 1205;
UPDATE skyfire_string SET content_loc2 = 'La bataille va commencer dans 1 minutes.' WHERE entry = 1206;
UPDATE skyfire_string SET content_loc2 = 'Que la bataille commence !' WHERE entry = 1208;
UPDATE skyfire_string SET content_loc2 = 'La bataille commencera dans 30 secondes.' WHERE entry = 1207;
UPDATE skyfire_string SET content_loc2 = 'L\'alliance maintient' WHERE entry = 1209;
UPDATE skyfire_string SET content_loc2 = 'La horde maintient' WHERE entry = 1210;
UPDATE skyfire_string SET content_loc2 = '%s victoire!' WHERE entry = 1211;
UPDATE skyfire_string SET content_loc2 = 'La porte ouest de %s est detruite!' WHERE entry = 1212;
UPDATE skyfire_string SET content_loc2 = 'La porte est de %s est detruite!' WHERE entry = 1213;
UPDATE skyfire_string SET content_loc2 = 'La porte sud de %s est detruite!' WHERE entry = 1214;
UPDATE skyfire_string SET content_loc2 = 'La porte nord de %s est detruite!' WHERE entry = 1215;
UPDATE skyfire_string SET content_loc2 = '$n a attaqué %s !' WHERE entry = 1216;
UPDATE skyfire_string SET content_loc2 = '$n a défendu %s' WHERE entry = 1217;
UPDATE skyfire_string SET content_loc2 = '$n a attaque %s! Si rien n\'est fait, %s le contrôlera dans 1 minute!' WHERE entry = 1218;
UPDATE skyfire_string SET content_loc2 = '%s a pris %s' WHERE entry = 1219;
UPDATE skyfire_string SET content_loc2 = 'L\'Atelier' WHERE entry = 1220;
UPDATE skyfire_string SET content_loc2 = 'Les Docks' WHERE entry = 1221;
UPDATE skyfire_string SET content_loc2 = 'La Raffinerie' WHERE entry = 1222;
UPDATE skyfire_string SET content_loc2 = 'La Carriere' WHERE entry = 1223;
UPDATE skyfire_string SET content_loc2 = 'Le Hangar' WHERE entry = 1224;
UPDATE skyfire_string SET content_loc2 = 'L\'envoi de requête MJ est autorisé' WHERE entry = 1134;
UPDATE skyfire_string SET content_loc2 = 'L\'envoi de requêtes MJ n\'est pas autorisé' WHERE entry = 1135;
UPDATE skyfire_string SET content_loc2 = 'Donne le contrôle a la premiere personne qui joint le canal "%s": désactive.' WHERE entry = 5023;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde a été pris pas $n!' WHERE entry = 1240;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la horde a été remis dans sa base $n!' WHERE entry = 1239;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été remis dans sa base $n!' WHERE entry = 1238;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été échappé par $n!' WHERE entry = 1237;
UPDATE skyfire_string SET content_loc2 = 'Le drapeay de la Horde a été échappé par $n!' WHERE entry = 1236;
UPDATE skyfire_string SET content_loc2 = '$n a capturé le drapeau de l\'Alliance !' WHERE entry = 1235;
UPDATE skyfire_string SET content_loc2 = '$n a capturé le drapeau de la Horde !' WHERE entry = 1234;
UPDATE skyfire_string SET content_loc2 = 'Que la bataille pour les crêtes jumelles commence !' WHERE entry = 1233;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour les crêtes jumelles commence dans 30 secondes. Préparez vous !' WHERE entry = 1232;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour les crêtes jumelles commence dans 1 minute.' WHERE entry = 1231;
UPDATE skyfire_string SET content_loc2 = 'La bataille pour les crêtes jumelles commence dans 2 minutes.' WHERE entry = 1230;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été pris par $n!' WHERE entry = 1241;
UPDATE skyfire_string SET content_loc2 = 'Les drapeaux sont désormais dans leur bases.' WHERE entry = 1242;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de l\'Alliance a été remis dans sa base.' WHERE entry = 1243;
UPDATE skyfire_string SET content_loc2 = 'Le drapeau de la Horde a été remis dans sa base.' WHERE entry = 1244;
UPDATE skyfire_string SET content_loc2 = 'Requiert Damoiselle du lac du Souffle de l\'hiver' WHERE entry = 1334;
UPDATE skyfire_string SET content_loc2 = 'Vous ne pouvez l\'utiliser maintenant .' WHERE entry = 1335;
UPDATE skyfire_string SET content_loc2 = 'La bataille de Gilnéas commence dans 2 minutes.' WHERE entry = 1250;
UPDATE skyfire_string SET content_loc2 = 'La bataille de Gilnéas commence dans 1 minute.' WHERE entry = 1251;
UPDATE skyfire_string SET content_loc2 = 'La bataille de Gilnéas commence dans 30 secondes. Préparez vous !' WHERE entry = 1252;
UPDATE skyfire_string SET content_loc2 = 'La bataille de Gilnéas commence!' WHERE entry = 1253;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance' WHERE entry = 1254;
UPDATE skyfire_string SET content_loc2 = 'La Horde' WHERE entry = 1255;
UPDATE skyfire_string SET content_loc2 = 'phare' WHERE entry = 1256;
UPDATE skyfire_string SET content_loc2 = 'usines hydrauliques' WHERE entry = 1257;
UPDATE skyfire_string SET content_loc2 = null WHERE entry = 1258;
UPDATE skyfire_string SET content_loc2 = 'Les %s a pris le contrôle de %s' WHERE entry = 1259;
UPDATE skyfire_string SET content_loc2 = '$n a défendu %s !' WHERE entry = 1260;
UPDATE skyfire_string SET content_loc2 = '$n a attaqué %s !' WHERE entry = 1261;
UPDATE skyfire_string SET content_loc2 = '$n a attaque %s! Si rien n\'est fait, %s le contrôlera dans 1 minute!' WHERE entry = 1262;
UPDATE skyfire_string SET content_loc2 = 'L\'Alliance a recueilli $1776W resources, et est proche de la victoire!' WHERE entry = 1263;
UPDATE skyfire_string SET content_loc2 = 'La Horde a recueilli $1777W resources, et est proche de la victoire!' WHERE entry = 1264;


