/*
SET NAMES utf8;                        
*/







UPDATE `locales_page_text` SET `Text_loc2` = 'Bonjour Morgan,\n\nLes affaires sont florissantes à Comté-de-l’or, au point que je n\'ai pas eu le temps de vous envoyer la moindre cargaison !  \n\nJ\'ai demandé au porteur de ce message de vous remettre un grand paquet de bougies (vous savez, celles que les kobolds aiment porter sur le sommet du crâne ?) \n\nRemerciez ce messager et donnez-lui le paiement qui lui revient.' WHERE `entry` = 15;
UPDATE `locales_page_text` SET `Text_loc2` = 'RAPPORT : Les kobolds\n\nL\'activité des kobolds s\'est accrue dans les pourtours de la vallée de Comté-du-nord. Ils ont établi un campement au nord de l\'abbaye et se rassemblent dans la mine d\'Echo en nombre effrayant. J\'ai fait prêter serment aux paladins, aux guerriers et aux habitants du cru pour qu\'ils m\'aident à éliminer cette vermine.\n\nTout se passe bien. Je donnerai plus de nouvelles quand la situation aura évolué.' WHERE `entry` = 209;
UPDATE `locales_page_text` SET `Text_loc2` = 'RAPPORT : Les voleurs\n\nPlus inquiétants que les kobolds, une bande humaine de voleurs a fait son apparition dans la vallée. Ils portent des foulards rouges et se désignent comme une confrérie. Une telle organisation peut apporter bien des ennuis, ici comme dans toute la forêt d\'Elwynn.\n\nNous avons identifié un de leurs chefs, un certain Garrick Ladétrousse, et nous espérons le présenter prochainement à la justice.' WHERE `entry` = 210;
UPDATE `locales_page_text` SET `Text_loc2` = 'RAPPORT : Les loups\n\nOn signale des attaques d\'animaux de plus en plus nombreuses à Comté-du-nord. Eagan pense que les loups de la vallée viennent du bois de la Pénombre, d\'où ils ont été effrayés.\n\nLes loups chassent rarement les humains, mais rien que leur nombre provoque des incidents avec les fermiers. Et de nombreuses bêtes ont disparu.' WHERE `entry` = 211;
UPDATE `locales_page_text` SET `Text_loc2` = 'RECOMMANDATION :\n\nLe porteur de ce document a été nommé adjoint dans l\'armée de Hurlevent, ayant servi Comté-du-nord avec dévouement et courage. Je ne doute pas que vous trouviez ses services utiles dans la forêt d\'Elwynn.\n\nSigné :\n-Maréchal Douglas McBride, \nArmée de Hurlevent, Comté-du-nord' WHERE `entry` = 212;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 1 :\n6H - 11H - camp supérieur\n11H - 11H30 - Pause, déjeuner\n11H30 - 16H00 - passe du canyon\n16H00 - 19H30 - camp supérieur\n\nJour 2 :\nIdem jour 1\n\nJour 3 :\nIdem\n\nJour 4 :\nIdem, à une exception. Juste avant le crépuscule, Thorsen m\'a demandé de le couvrir pendant qu\'il s\'enfonçait dans la passe du canyon. Je suppose qu\'il est allé rencontrer un de nos agents.\n\nMais il est revenu une heure plus tard. Cela m\'a surpris. J\'espérais qu\'il avait rencontré un de nos agents et rejoint Kurzen. Quelque chose ne va pas.' WHERE `entry` = 311;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 5 :\nThorsen était très agité aujourd\'hui. Quoi qu\'il ait vu ou qui qu\'il ait rencontré durant son excursion d\'hier, il a eu peur.\n\nJe suppose que nos agents lui ont parlé, mais lorsque j\'ai demandé à Thorsen où il était allé pendant que je le couvrais, il est resté silencieux. Il me pense son ami, et croit me protéger contre un dangereux secret.\n\nIl place mal sa loyauté, mais il est loyal. Quand il nous rejoindra, il sera un apport inestimable aux forces de Kurzen.' WHERE `entry` = 312;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 6 :\nTôt ce matin, Thorsen a longuement parlé avec le sergent Yohwa. J\'ai dû faire semblant de dormir et je n\'ai pu m\'approcher pour les écouter. Mais je pense qu\'ils parlaient de l\'excursion récente de Thorsen.\n\nJe l\'ai attentivement observé au déjeuner et j\'ai vu que Yohwa en faisait autant. Plus tard, Doren a convoqué Thorsen. Tous trois partagent un secret. Doren et Yohwa doivent savoir que Thorsen rencontre vos agents.\n\nIl espionne les rebelles.' WHERE `entry` = 313;
UPDATE `locales_page_text` SET `Text_loc2` = 'Dun Modr des Paluns\n\nMa chère Sara,\n\nTout porte à croire que nous allons partir dans quelques jours assurer la garde du viaduc de Thandol. Je ne pourrai plus vous écrire. Je ressens le besoin de vous écrire quelques lignes qui pourront vous atteindre lorsque je ne serai plus.' WHERE `entry` = 317;
UPDATE `locales_page_text` SET `Text_loc2` = 'Notre mission peut être courte et pleine de réjouissances ou apporter la mort après de rudes combats. S\'il me faut tomber pour l\'Alliance sur le champ de bataille, je suis prêt. \n\nJe n\'ai pas le moindre doute sur la cause pour laquelle je me bats et mon courage ne connaît pas de trouble.' WHERE `entry` = 318;
UPDATE `locales_page_text` SET `Text_loc2` = 'Je sais à quel point le royaume de Forgefer dépend du triomphe de l\'Alliance, et la dette que nous avons envers ceux qui sont tombés avant nous dans les Grandes Guerres. Je suis prêt, vraiment prêt, à abandonner toutes les joies de l\'existence pour aider à maintenir l\'Alliance et pour payer cette dette.' WHERE `entry` = 319;
UPDATE `locales_page_text` SET `Text_loc2` = 'Sara, mon amour pour vous est éternel, j\'ai l\'impression d\'être uni à vous par de solides liens que seule une divinité pourrait briser, et mon amour pour le royaume est comme un vent puissant qui me porte irrésistiblement, avec ces chaînes, sur le champ de bataille.' WHERE `entry` = 320;
UPDATE `locales_page_text` SET `Text_loc2` = 'La mémoire de tous les heureux moments que j\'ai passés avec vous ne cesse de me hanter et je remercie infiniment la Lumière de les avoir connus. Il est très dur pour moi de laisser tout ceci derrière moi et de voir réduits en cendres les espoirs des années à venir que nous aurions vécues ensemble en voyant nos fils devenir d\'honorables nains.' WHERE `entry` = 321;
UPDATE `locales_page_text` SET `Text_loc2` = 'Je sais que je ne suis rien dans les desseins de la Divine Providence, mais quelque chose me murmure (peut-être est-ce la prière de mon petit Edgar) que je reviendrai sans mal vers ceux que j\'aime. Si tel n\'est pas le cas, ma bien-aimée Sara, n\'oubliez jamais combien je vous aime et sachez que lorsque j\'exhalerai mon dernier souffle ce sera en murmurant votre nom. \n\nPardonnez mes fautes et les douleurs que je vous ai causées, pardonnez mon manque d\'attention, ma stupidité.' WHERE `entry` = 322;
UPDATE `locales_page_text` SET `Text_loc2` = 'Avec quel bonheur je laverais de mes larmes la moindre tache sur votre bonheur et me battrais contre toutes les infortunes de ce monde pour vous protéger du mal, ainsi que mes chers enfants.\n\nMais c\'est impossible. \n\nJe vous regarderai depuis le Néant distordu et je veillerai sur vous tandis que vous affronterez les tempêtes du haut de votre frêle taille, attendant que nous nous rejoignions pour toujours.' WHERE `entry` = 323;
UPDATE `locales_page_text` SET `Text_loc2` = 'Mais, ô ma Sara, si les morts peuvent revenir à Azeroth et entourer, invisibles, ceux qu\'ils aiment, je serai toujours à vos côtés dans les jours heureux comme dans les nuits les plus sombres, partageant vos heures de joie comme vos moments de tristesse. Si jamais vous sentez une douce brise sur votre joue, ce sera mon souffle ; si l\'air rafraîchit vos tempes, ce sera mon esprit qui passe.\n\nSara, ne me pleurez pas, pensez que je suis parti et que je vous attends, car nous nous reverrons.\n\n—Sully' WHERE `entry` = 332;
UPDATE `locales_page_text` SET `Text_loc2` = 'Aux Schneider,\n\nSalutations. J\'espère que les affaires vont bien. Dans le quartier commerçant, c\'est l\'explosion.\n\nNous avons grand besoin de tricots, car nos stocks sont vides. Veuillez nous envoyer le chargement habituel dès que vous le pourrez.\n\nJe vous souhaite bonne fortune et j\'espère que les études de votre fils Thurman progressent bien,\n\n—Harlan Bagley' WHERE `entry` = 336;
UPDATE `locales_page_text` SET `Text_loc2` = 'L\'Étoile de Xil\'yeh\n\nGrel\'borg l\'Avare a l\'Étoile. C\'est un ogre cupide qui passe ses journées dans les montagnes d\'Alterac, au cœur des ruines d\'Alterac, à chercher des babioles. La majeure partie de sa collection est sans intérêt, mais un des objets, l\'Étoile de Xil\'yeh, a des capacités intéressantes.' WHERE `entry` = 372;
UPDATE `locales_page_text` SET `Text_loc2` = 'La Main de Dagun\n  \nDes textes anciens affirment que les griffes de Dagun sécrètent un poison qui non seulement tue sa proie, mais la fait muter en quelque chose d\'autre, en un membre des vieilles races. Sa valeur est évidente pour nous.\n\nDagun vit dans la mer profonde, mais il est régulièrement attiré à la surface par une tribu de murlocs Aileron boueux du marécage d\'Âprefange. Leurs oracles l\'invoquent avec du varech enchanté. Si vous tuez assez d\'oracles, vous trouverez le varech. Placez-le ensuite sur l\'autel des murlocs et Dagun apparaîtra.' WHERE `entry` = 373;
UPDATE `locales_page_text` SET `Text_loc2` = 'Le Cœur de l\'héritage\n\nMogh l\'Immortel est un sorcier-docteur troll de Strangleronce. Il possède le Cœur de l\'héritage, qui a réputation d\'éloigner la mort de ceux qui savent découvrir son secret. Vous trouverez Mogh dans les ruines de Zul\'Mamwe. Battez-le, si vous pouvez, et apportez-moi le Cœur de l\'héritage.' WHERE `entry` = 374;
UPDATE `locales_page_text` SET `Text_loc2` = 'Apportez-moi ces trois objets, l\'Étoile, la Main et le Cœur, et l\'Abrégé de Yagyin sera à vous.\n\n-G.B.' WHERE `entry` = 375;
UPDATE `locales_page_text` SET `Text_loc2` = 'Notre plan est en train de se réaliser.\n\nPrenez cet ancien bastion de la foi, la Veillée des héros, pour en faire notre base, et nous commencerons à vous envoyer des renforts de la marche de l\'Ouest, une fois que vous nous aurez fait savoir que le site a été préparé.\n\nCet endroit est quasiment oublié des citoyens et soldats de Hurlevent et fera un avant-poste parfait pour lancer nos attaques.\n\nLes Defias reprendront Hurlevent !\n\nJ\'attends votre réponse.' WHERE `entry` = 811;
UPDATE `locales_page_text` SET `Text_loc2` = 'Cette preuve atteste que $N a tué Margol l\'Enragée, fléau de la gorge des Vents brûlants.\n\nLe musée de Forgefer reconnaît cet exploit, remercie le porteur de la nouvelle et se réjouit de cette généreuse contribution. \n\n-Conservateur en chef Thorius Soignepierre' WHERE `entry` = 1231;
UPDATE `locales_page_text` SET `Text_loc2` = 'Frère Neals,\n\nMes raisins sont sauvés ! $N, qui vous apporte ce manifeste, a réussi à braver l\'adversité et à récupérer les raisins. Bien que les Défias continuent à sévir sur les berges de la rivière, presque toute ma récolte a été sauvée.\n\nVous pourrez ajouter bien des boisseaux à vos échoppes.\n\nQue la Lumière nous protège,\n-Milly Osworth' WHERE `entry` = 1392;
UPDATE `locales_page_text` SET `Text_loc2` = 'Salutations, Aventuriers !\n\nMoi, Froisse Bonnacier, j\'ai besoin de ceux qui sont capables de prendre beaucoup de risques pour achever les tâches les plus ardues. En raison de mes nombreux devoirs et des charges que j\'ai dû endosser, je m\'assurerai que quiconque est assez brave pour rapporter cette liste d\'objets intacts soit grassement récompensé. \n\nLa liste est contenue dans les pages suivantes...' WHERE `entry` = 1551;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les pouvoirs presque sans limite de Sargeras étaient bien suffisants pour détruire les ignobles érédars, mais le titan fut troublé par la corruption de ces créatures et par le Mal qui consumait tout sur son passage. Incapable de comprendre cette dépravation et cette malveillance, le grand titan tomba dans une dépression sans fin. En dépit de son malaise grandissant, Sargeras chercha à débarrasser l\'univers des sorciers à jamais, en les enfermant dans une cellule de vide au cœur du Néant distordu.' WHERE `entry` = 1775;
UPDATE `locales_page_text` SET `Text_loc2` = 'Le noble Sargeras, incapable de lutter contre les doutes et le désespoir frénétiques qui accablaient sa raison, perdit foi non seulement en sa mission mais aussi en la vision des titans d\'un univers ordonné. Sargeras commença à croire que le concept même d\'ordre était pure démence, et que le chaos et la dépravation étaient les seuls absolus dans le vaste univers sombre et solitaire.' WHERE `entry` = 1778;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les autres titans tentèrent de le convaincre de son erreur et de mettre du baume sur son cœur meurtri, mais il repoussa leurs arguments comme de simples illusions. Sargeras quitta leurs rangs pour toujours afin de trouver sa propre place dans l\'univers. Le Panthéon fut attristé de son départ mais ne pouvait imaginer ce qu\'il adviendrait de lui.' WHERE `entry` = 1779;
UPDATE `locales_page_text` SET `Text_loc2` = 'Tandis que la folie de Sargeras détruisait les derniers vestiges de son noble esprit, il commença à penser que les titans étaient les vrais responsables de l\'échec de la création. Il décida finalement de détruire leur travail à travers tout l\'univers et il commença à rassembler une armée invincible qui nettoierait l\'univers physique par le feu.' WHERE `entry` = 1780;
UPDATE `locales_page_text` SET `Text_loc2` = 'Kil’jaeden le Trompeur fut choisi pour trouver les races les plus sombres de l\'univers et les attirer dans l\'ombre de Sargeras. Le second champion, Archimonde le Profanateur, fut choisi pour conduire les vastes armées de Sargeras au combat contre quiconque se dresserait contre le titan noir.' WHERE `entry` = 1783;
UPDATE `locales_page_text` SET `Text_loc2` = 'Contents que le petit monde ait été ordonné et que leur travail soit accompli, les titans se préparèrent à quitter Azeroth. Mais, avant de partir, ils décidèrent de donner aux plus grandes espèces nouvelles du monde le pouvoir de surveiller Kalimdor contre toute menace possible. A cette époque, il y avait de nombreuses tribus de dragons.' WHERE `entry` = 1795;
UPDATE `locales_page_text` SET `Text_loc2` = 'Il existait cinq tribus qui avaient la main-mise sur leurs frères. Ce sont ces cinq tribus que les titans choisirent pour contrôler le monde. Les plus grands membres du Panthéon donnèrent une partie de leur pouvoir au chef de chaque tribu. Ces dragons majestueux, dont les noms suivent, prirent le nom de Grands Aspects, ou Aspects dragons.' WHERE `entry` = 1796;
UPDATE `locales_page_text` SET `Text_loc2` = 'Eonar, le titan responsable de la vie, donna une portion de sa puissance au léviathan rouge, Alexstrasza. Alexstrasza fut désormais connue comme la Lieuse de vie et elle travailla à sauvegarder les créatures vivantes du monde. En raison de sa sagesse sans bornes et de son infinie compassion pour toutes les espèces vivantes, Alexstrasza fut couronnée reine des dragons et reçut la tutelle de son espèce.' WHERE `entry` = 1798;
UPDATE `locales_page_text` SET `Text_loc2` = 'Norgannon, le titan gardien des traditions et de la magie, donna au dragon bleu Malygos une partie de ses vastes pouvoirs. Malygos, désormais Tisseur de sorts, devint le gardien de la magie et des arcanes cachées.' WHERE `entry` = 1800;
UPDATE `locales_page_text` SET `Text_loc2` = 'Khaz\'goroth, le titan qui forgeait les mondes, transmit un peu de son grand pouvoir au puissant Wyrm noir, Neltharion. Avec son grand cœur, Neltharion, qui prit le nom de Gardien du monde, reçut toute puissance sur la terre et les vastes espaces du monde. Il personnifia la force du monde et devint le plus ardent soutien d\'Alexstrasza.' WHERE `entry` = 1801;
UPDATE `locales_page_text` SET `Text_loc2` = 'Ainsi nantis de différents pouvoirs, les cinq Aspects furent chargés de la défense du monde en l\'absence des titans. Les dragons étant prêts à défendre leur création, les titans quittèrent Azeroth pour toujours. Malheureusement pour eux, et pour le petit monde qu\'ils venaient de façonner, Sargeras finirait un jour ou l\'autre par découvrir son existence...' WHERE `entry` = 1802;
UPDATE `locales_page_text` SET `Text_loc2` = 'Sous la garde vigilante de l\'Ordre de Tirisfal, Dalaran devint la principale ville d\'apprentissage des magiciens. Les magiocrates qui dirigeaient Dalaran fondèrent le Kirin Tor, une secte spécialisée qui avait pour charge de faire l\'inventaire des sorts, des artéfacts et des objets magiques connus de l\'humanité, et de les étudier.' WHERE `entry` = 1899;
UPDATE `locales_page_text` SET `Text_loc2` = 'Ragnaros le seigneur des flammes, maître immortel des élémentaires du feu, avait été banni par les titans à l\'aube du monde. Libéré par l\'appel de Thaurissan, Ragnaros réapparut à la surface du globe. Sa renaissance apocalyptique dans Azeroth fissura les montagnes Carmines et fit surgir un volcan ardent au centre de la région dévastée.' WHERE `entry` = 1924;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les combats épiques de la Deuxième guerre incluaient des engagements aériens aussi bien que de vastes batailles navales. La Horde était parvenue à déterrer un puissant artéfact nommé l\'Âme du démon et l\'avait utilisé pour réduire en esclavage la reine des dragons, Alexstrasza. Menaçant de détruire ses précieux œufs, la Horde força Alexstrasza à envoyer sa progéniture adulte au combat. Les nobles dragons rouges furent contraints de se battre pour la Horde, et ils le firent bien.' WHERE `entry` = 1981;
UPDATE `locales_page_text` SET `Text_loc2` = 'Kel’Thuzad ayant réussi à Lordaeron, le roi-liche s\'occupa des ultimes préparatifs de son assaut contre la civilisation humaine. Il enferma sa peste dans de nombreux artéfacts portables nommés chaudrons du fléau, puis ordonna à Kel’Thuzad de transporter les chaudrons vers Lordaeron où ils seraient placés dans différents villages contrôlés par le culte.' WHERE `entry` = 2054;
UPDATE `locales_page_text` SET `Text_loc2` = 'J\'espère que vous allez bien, $c. Je le dis avec fierté, car peu peuvent se targuer d\'une telle foi, mais ils font également partie de l\'élite vraie des protecteurs d\'Azeroth.$B$BSouvenez-vous toujours et avant tout que votre devoir est de vous battre contre ceux qui veulent blesser notre monde et corrompre nos foyers.$B$BJ\'ai reçu toute autorité pour vous former. Quand vous le voudrez, venez me voir à l\'Abbaye de Comté-du-nord.$B$B-Frère Sammuel, Maître des paladins' WHERE `entry` = 2463;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les nains$B$BLes nains sont obsédés par la recherche de leurs origines. Les nains ont choisi de célébrer la saison comme une reconnaissance de Grand-père Hiver lui-même. Ils considèrent qu\'il est la personnification d\'un membre des anciens d\'Azeroth : les titans. Bien qu\'ils revendiquent une descendance plus ou moins éloignée avec ces êtres mystiques, ils considèrent que Dun Morogh est le meilleur exemple des bienfaits de Grand-père Hiver.' WHERE `entry` = 2573;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les taurens$B$BLa légende du Voile de l\'hiver s\'accommode parfaitement de la vision chamaniste de l\'hiver des taurens et de leur intérêt récent pour le druidisme. Ils se focalisent presque entièrement sur les aspects de la tradition relatifs à la renaissance, laissant toute la partie cultuelle aux races qui, selon eux, sont moins en accord avec la nature des choses. De nombreux taurens considèrent cette époque comme le bon moment pour rendre grâce pour leur nouveau foyer en Mulgore.' WHERE `entry` = 2574;
UPDATE `locales_page_text` SET `Text_loc2` = 'Concours de pêche à Strangleronce!\n\n Dimanche après-midi de 14 h à 16 h !\n\nBaladez-vous le long de la côte de Strangleronce et guettez les bancs de courbines qui apparaîtront le long de la côte ! Envoyez votre flotteur dans le banc, et vous prendrez des poissons inhabituels au lieu des variétés normales de Strangleronce. Le premier à pêcher quarante courbines et à se présenter au maître de pêche Perchappât, à Baie-du-Butin, recevra un prix !  \n\nMême si vous n’êtes pas le premier à prendre quarante courbines, vous pouvez toujours vous présenter pour les revendre. Et puis, il existe aussi des poissons spéciaux, pour lesquels il y a des récompenses particulières !' WHERE `entry` = 2786;
UPDATE `locales_page_text` SET `Text_loc2` = 'J’espère de tout mon cœur que mes recherches permettront de découvrir une source d’énergie magique complémentaire dans laquelle mon peuple pourra puiser sans danger. Avec la disparition du puits de soleil, nous devons trouver un moyen de perpétuer notre mode de vie sans succomber aux pièges de la magie des arcanes.\n\nJe crois que dans l’avenir, les sin’dorei deviendront, une fois encore, un exemple éclatant que tous pourront suivre !' WHERE `entry` = 2846;
UPDATE `locales_page_text` SET `Text_loc2` = 'Aucun succès jusqu’à présent. Le peu de magie dont je peux disposer doit être canalisé par la flèche. J’ai quand même eu quelques idées intéressantes. J’ai chargé mes apprentis les plus brillants de suivre ces pistes. Nous verrons bien ce qu’il en sort.' WHERE `entry` = 2847;
UPDATE `locales_page_text` SET `Text_loc2` = 'Je n’ai rien écrit ici depuis un moment. Toujours rien de prometteur. J’ai appris hier que l’un des disciples de l’île de Haut-soleil, un certain Felendren, avait ignoré les conseils de ses mentors et avait succombé au mal.\n\nJe vais redoubler d’efforts.' WHERE `entry` = 2848;
UPDATE `locales_page_text` SET `Text_loc2` = 'Rien, mais je ne dois pas perdre espoir. Les Sin’dorei ne peuvent pas se permettre de dépendre de la magie au moment où nous sommes assiégés depuis le sud.\n\nJ’ai envisagé une approche entièrement nouvelle. Si elle réussit, elle nous permettra de filtrer les « impuretés » de certaines sources d’énergie corrompues et gangrenées que j’avais mises de côté jusqu’à présent. Je dois me montrer prudent.' WHERE `entry` = 2849;
UPDATE `locales_page_text` SET `Text_loc2` = 'Extraordinaire ! Nous avons remporté quelques succès, bien que la quantité de magie que nous avons été capable d’extraire soit encore très minime. Je vais demander à la plupart des apprentis d’interrompre leurs études pour se concentrer sur cette nouvelle approche si prometteuse.\n\nAvec un peu de chance, nous serons bientôt capables d\'affiner le processus. Cela nous permettrait de faire d’une pierre deux coups : nous procurer une source de magie abondante ET un moyen de contrer les magies gangrenées que nous risquons de rencontrer à l’avenir !' WHERE `entry` = 2850;
UPDATE `locales_page_text` SET `Text_loc2` = 'Non ! J’expérimentais le nouveau processus avec mon apprenti principal, Telethayon. Soudain, il s’est flétri sous mes yeux, succombant au mal qui afflige les miens. J’ai essayé de le sauver, mais il était trop gravement touché. Je n’ai pu que mettre un terme à ses souffrances.\n\nTel est le prix de la découverte, un prix qui me semble déjà trop lourd.' WHERE `entry` = 2851;
UPDATE `locales_page_text` SET `Text_loc2` = 'C’est difficile à supporter… deux autres apprentis sont morts. Nous avons été si prudents… Je ne comprends pas ce qui a mal tourné.\n\nIl va falloir que j’abandonne cette piste, et que nous recommencions depuis le début.' WHERE `entry` = 2852;
UPDATE `locales_page_text` SET `Text_loc2` = 'Je suis arrivé trop tard. À mon insu, un troisième apprenti s’était ouvert de cet axe de recherche désastreux à certains de ses confrères. Je vais essayer d’endiguer la crise, mais je dois d’abord éloigner les apprentis qui ne sont pas affectés.\n\nJe vais leur annoncer à tous mon départ en congé sabbatique à la retraite des Pérégrins, dans l’espoir de trouver une nouvelle approche au problème.\n\nJe dois trouver un moyen de racheter cette horrible erreur.' WHERE `entry` = 2853;
UPDATE `locales_page_text` SET `Text_loc2` = 'C\'est moi qui l\'ai fait. Je ne m\'en souviens pas, mais cela n\'a pu se passer qu\'ainsi.$B$BJ\'ai déjà commis de nombreuses fautes au cours de mon existence. J’ai même tué un homme qui ne l’avait pas mérité. Mais ceci est différent.$B$BJ’ai changé.$B$BJe n’ai pas choisi de commettre ces meurtres. Une bête vit en moi.$B$BJe serai pourchassé et ostracisé. Il faut que je me cache. Que je m’enfuie. Que j’enterre les corps.$B$BJ’ai commencé à marcher dehors quand j’ai compris ce qui me troublait vraiment.$B$BJe n’éprouve aucun remords.' WHERE `entry` = 2918;
UPDATE `locales_page_text` SET `Text_loc2` = 'Goramosh,\n\nJe vous envoie un représentant de l’Ethereum. L’ambassadeur Duyheen m’a dit que d’autres membres de son groupe aimeraient se joindre à notre cause. Sondez-le, voyez si vous pouvez lui trouver une utilité.\n\nS’il peut nous servir, j’envisagerai d’en recruter d’autres.\n\nNe soyez pas stupide, brûlez cette lettre dès que vous l\'aurez lue !\n\nM' WHERE `entry` = 3067;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 1 : la vermine humaine semble béatement inconsciente de ma présence, comme prévu. Ils sont mûrs pour un bombardement, et ce n\'est qu\'une question de temps avant que j\'aie cartographié leur position.\n\nJour 2 : carte terminée - une besogne bien triviale pour quelqu\'un d\'aussi accompli que moi. Je n\'arrive pas à saisir pourquoi j\'ai écopé de ce travail, ils auraient dû y coller J-Y C. Cet accent ridicule devrait suffire à justifier sa désignation.\n\nJour 3 : le premier souffle d\'air commence à être un peu éventé. Je devrais peut-être faire momentanément surface dans quelques jours pour en prendre un autre. Je m\'ennuie toujours à mourir ; où est ce maudit signal ?\n\n<Les divagations continuent...>' WHERE `entry` = 3103;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 12 : ah, le délicieux soulagement. La seconde respiration avait le goût des larmes d\'orphelins les plus pures que j\'aie connues. Le signal est toujours bizarrement absent, et je pourrais jurer que l\'un des crabes essaye de jouer du tambour sur mon gros orteil.\n\n<Les divagations se font plus décousues...>' WHERE `entry` = 3104;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 36 : j\'ai finalement expiré mon troisième souffle, et les veines de mon épaule gauche se sont encore remplies de bulles pendant ma remontée. Le tambourinement des crabes est devenu un accompagnement constant, le décor sonore de mon petit coin d\'enfer obscur. À l\'évidence, ces misérables m\'ont oublié. Si J-Y était ici, ils ne l\'auraient pas oublié, lui ! Ils n\'abandonneraient pas Hans ou Sylvia ! Alors pourquoi moi ?\n\n<L\'écriture se transforme en gribouillages cafardeux...>' WHERE `entry` = 3105;
UPDATE `locales_page_text` SET `Text_loc2` = 'L\'ami d\'un mage n\'aura jamais faim ni soif. Et la nourriture invoquée ne contient pas de graisses transmutées !\n\nVous pensez qu\'une chope glacée est le meilleur moyen de conserver votre bière fraîche ? Vous devriez voir une chope qui a reçu un éclair de givre !\n\nDes études montrent que la plupart des chefs-d\'œuvre de la litterature ont été écrits alors que l\'auteur était sous l\'influence d\'Intelligence des arcanes.' WHERE `entry` = 3308;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée 2\n\nLa destruction continua pendant des heures. J\'étais certain que chaque nouvelle secousse tonitruante serait la fin. Malgré cela, je restais recroquevillé sous une arche qui encadrait autrefois notre vue sur les rues animées du marché. Combien de fois avais-je vu ma sœur en revenir, les bras chargés de marchandises ? Désormais, seules la poussière et la pierre se tiennent devant moi.' WHERE `entry` = 3354;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée 4\n\nJe dois croire dans le Kirin Tor. Les grands mages de Dalaran n\'abandonneraient pas leur peuple. Ce gravat qui m\'emprisonne n\'est rien qu\'une bagatelle pour un lanceur de sorts doué. Je serai sauvé, puis un jour, je terminerai mon entraînement et j\'aurai ma place parmi eux.' WHERE `entry` = 3355;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée 5\n\nAucun signe des autres ou de ma famille. Je les ai appelés. Là-haut, tout est silencieux maintenant. Je ne sais pas si je dois me considérer comme chanceux ou maudit. Mon cœur voudrait trouver le calme et suivre les autres dans le repos, mais mon esprit est envahi par la peur.' WHERE `entry` = 3356;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée 6\n\nIl fait de plus en plus noir et l\'air se raréfie. Les faibles lumières que j\'invoque pour écrire me brûlent les yeux. Je ne peux plus continuer. Je dois garder mon énergie pour le cas où il se passerait quelque chose. J\'ai l\'audace d\'espérer que ces bouts de papier survivront au silence puisque je ne le peux pas. Je deviendrai une voix, chantant à travers cet abysse, se voilant jusqu\'à devenir un murmure, puis disparaissant dans le ciel.' WHERE `entry` = 3357;
UPDATE `locales_page_text` SET `Text_loc2` = 'L\'invocation enseigne comment invoquer les créatures tout comme les objets. Vous n\'avez jamais eu envie de boire de l\'eau de source bien fraîche alors que vous étiez au milieu de nulle part ? L\'invocation, mon $gami:amie;, est la solution. Il n\'y a rien de plus agréable pour un mage que de créer une tranche de pain frais ou un verre d\'eau. Demandez à n\'importe lequel d\'entre nous !' WHERE `entry` = 3367;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les spécialistes de l\'invocation les plus impressionnants peuvent invoquer plusieurs verres d\'eau d\'un coup, ou peut-être même une chope. Une poignée de sorciers plus aventureux ont parfois essayé d\'invoquer de l\'eau sans penser au verre, et c\'est ainsi que l\'art d\'invoquer des élémentaires d\'eau est né. Les élémentaires d\'eau sont les meilleurs amis d\'un sorcier. (Les grangrechiens ne sont pas, en fait, amicaux du tout.) Un élémentaire invoqué est un formidable allié au combat, un merveilleux auditeur, et il a même bon goût !' WHERE `entry` = 3368;
UPDATE `locales_page_text` SET `Text_loc2` = 'Plusieurs sorciers ont choisi de suivre le chemin rafraîchissant de l\'invocation. Le capitaine Balinda Gîtepierre est un excellent exemple de mage qui a choisi d\'adapter la magie de l\'invocation au combat. Cependant, le plus célèbre invocateur de notre temps fut peut-être le très aimé archimage Nileas Aran. Aran était non seulement célèbre pour sa capacité à invoquer plusieurs élémentaux d\'un coup, mais aussi pour avoir perfectionné une recette pour l\'invocation de cidre pétillant. Il faut également ajouter que Nileas Aran n\'était pas un simple bouffon. C\'est cela, l\'essence de la magie.' WHERE `entry` = 3369;
UPDATE `locales_page_text` SET `Text_loc2` = 'La neuvième et dernière école de magie est la transmutation. C\'est l\'une des écoles de magie les plus populaires et les plus utiles, qui permet à un mage de manipuler le temps et l\'espace. Le sort de transmutation le plus emblématique est la Métamorphose, qui permet à un mage de transformer quelque chose - ou quelqu\'un - en quelque chose d\'autre. Heureusement pour nombre de mes étudiants, les effets ne sont pas permanents. J\'ai vu plus d\'un apprenti inattentif transformé en mouton, cochon ou pire - ne me demandez pas ce que « pire » peut signifier.' WHERE `entry` = 3388;
UPDATE `locales_page_text` SET `Text_loc2` = 'Assurez-vous bien que vous connaissez votre destination avant de tenter de vous téléporter. Il y a une raison pour laquelle nous avons des sorts très spécifiques pour nous téléporter à certains endroits - essayer de lancer une téléportation « sans réfléchir » a souvent pour conséquence un mage très très mort dans un mur, un fauteuil ou un autre mage. Et quand je dis « dans », ça n\'a rien d\'agréable.' WHERE `entry` = 3390;
UPDATE `locales_page_text` SET `Text_loc2` = 'Gravement blessé ? On s\'occupe de vous ! LAVOMALTINE vous donnera l\'énergie supplémentaire dont vous avez besoin pour rejoindre un lieu sûr !*\nVous aimez le feu ? N\'avez-vous jamais pensé que ce serait génial de boire du feu liquide ? Si c\'est le cas, vous allez adorer la nouvelle LAVOMALTINE de Pyroco ! C\'est d\'la dynamique !\n\n*De récentes études ont démontré qu\'en réalité, il est possible que Lavomaltine ne contribue pas à soigner les blessures de quelque façon que ce soit. Il existe même une possibilité que Lavomaltine provoque d\'abondants saignements au niveau d\'orifices apparemment aléatoires.' WHERE `entry` = 3399;
UPDATE `locales_page_text` SET `Text_loc2` = 'Avertissement : Lavomaltine n\'est pas pour tout le monde. Les femmes enceintes, les femmes susceptibles de le devenir et les enfants doivent consulter leur médecin avant de boire Lavomaltine.' WHERE `entry` = 3400;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les effets secondaires peuvent comprendre : bouche sèche, nausée, yeux secs, indigestion, mal de dos, douleurs lombaires, douleurs articulaires, défiguration légère, hémorragie interne, folie temporaire, dépendance à la Lavomaltine, dépendance à la magie, pyromanie, arachnophobie, yeux lançant des éclairs, palpitations cardiaques, fièvre, accouchement spontané, perte du sommeil, vulnérabilité au fer froid, hystérie, chansons surgissant de manière aléatoire dans votre tête, asthme, possession démoniaque, maux de tête, maux de pieds, impossibilité d\'utiliser la lettre « R », mort.' WHERE `entry` = 3401;
UPDATE `locales_page_text` SET `Text_loc2` = 'Avertissement : boire plusieurs Lavomaltines à la suite peut entraîner des combustions spontanées.\n\nGoûtez la nouvelle LAVOMALTINE dès maintenant !' WHERE `entry` = 3402;
UPDATE `locales_page_text` SET `Text_loc2` = 'Bientôt, ils furent à la porte d\'Antonidas, cherchant à détruire Dalaran et à prendre le livre de Medivh, avec lequel ils prévoyaient d\'invoquer le démon Archimonde.\n\nAntonidas s\'éleva contre Arthas et son armée de morts-vivants, refusant d\'abandonner le livre ou la ville. Utilisant ses dons inégalés en magie défensive, Antonidas établit un champ magique qui détruisait tout mort-vivant le touchant (une version précoce des champs défensifs utilisés de nos jours).' WHERE `entry` = 3415;
UPDATE `locales_page_text` SET `Text_loc2` = 'Malheureusement, ce ne fut pas suffisant, et Arthas trouva un moyen de dissiper l\'enchantement. Il se dirigea droit sur Dalaran et assassina Antonidas de sang-froid. Kel\'Thuzad et Arthas entrèrent dans la citadelle Pourpre, prirent le livre de Medivh et invoquèrent Archimonde.\n\nQuand l\'armée de morts-vivants quitta la ville à la recherche de nouvelles cibles, Archimonde démolit ses structures, faisant s\'effondrer ses flèches magiques. Le Dalaran d\'Antonidas, désormais sans dirigeant et ressemblant à un champ de bataille, n\'était plus.' WHERE `entry` = 3416;
UPDATE `locales_page_text` SET `Text_loc2` = '[Épilogue]\n\nTombé au combat pour la défense du seul foyer qu\'il ait connu, Antonidas continue d\'être un exemple pour ceux qui survivent. Ses exploits, sa bravoure et son souvenir sont un témoignage de la volonté de vivre du vieux monde et de son nouvel héritage. Dans ce monde en constante guerre, les liens fragiles d\'une nouvelle Alliance ne sont qu\'un hommage à la mémoire et à la ténacité de l\'un des plus courageux héros de Lordaeron.' WHERE `entry` = 3417;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 1 : ne pas transformer une créature d\'intelligence inférieure en une créature d\'intelligence supérieure : les fonctions cérébrales sont rarement transférées lors d\'une métamorphose, mais cela arrive parfois. Les créatures voraces comme les serpents ou les loups n\'ont pas besoin de voir leurs instincts de prédateur intégrés dans un esprit humain. Nous nous permettons de rappeler le cas de demande d\'indemnisations pour petit désastre 12651-b, « Bartholomé : le serpent qui maniait la serpe ».' WHERE `entry` = 3455;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 2 : utiliser des créatures simples pour vos sorts de métamorphose. De nombreux disciples rebelles approuvent les études sur les transformations en créatures exotiques, mais dans le but de réduire le budget d\'indemnités juridiques du Kirin Tor, nous ne tolérons plus ce type de créatures. Les moutons sont des créatures parfaitement adaptées à toutes les situations, mais d\'autres créatures sont également autorisées (lire la dernière parution du mensuel de Kirin Tor pour la liste mise à jour). Les transformations en limons, éthériens, silithides, ou pire encore, draconiens, seront sévèrement punies. Ce qui nous amène à...' WHERE `entry` = 3456;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 3 : les excès en matière de métamorphoses doivent être gérés DISCRÈTEMENT et rapidement. Le public n\'a pas besoin de voir les horreurs qu\'un travail mal fait peut provoquer. Des accidents peuvent se produire, le Kirin Tor en est conscient. Mais la vision publique de baleines-garous, de murl-elfes, de worgens amphibiens, de limons volants, de grif-hippo-wyvernes, de lapins qiraji ou du tristement célèbre « cube à damiers bleus » nous donne mauvaise réputation à tous.' WHERE `entry` = 3457;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 4 : ne pas transformer une créature en une autre créature encore plus puissante. Bien que cela semble évident, nous nous permettons de rappeler le cas de demande d\'indemnisations pour désastre moyennement grave 8761-e, « Magus John Quint : liquéfié par un daim malade transformé en géant de lave violemment perturbé ».' WHERE `entry` = 3458;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 5 : ne pas transformer quoi que ce soit qui se trouve à mi-chemin dans un portail, on n\'a pas encore vu cela manquer de provoquer une explosion. Ce sujet est également évoqué dans « Réflexions sur les portails - Mémorandum sur l\'utilisation correcte des portails ».' WHERE `entry` = 3459;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 6 : ne pas transformer d\'objets inanimés ! Nous avons du mal à croire que le Kirin Tor puisse recevoir des plaintes à ce propos, mais un acte d\'une telle atrocité a provoqué le développement du tout nouveau cas de demande d\'indemnisations pour désastre extrêmement sévère 1-a, « Mon royaume pour un cheval : les cent cinquante raisons pour lesquelles on ne doit pas transformer un royaume en cheval ».\n<Ça continue comme ça sur des centaines de pages.>' WHERE `entry` = 3460;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 1 : ne jamais se transférer dans un espace déjà occupé. Le transfert, comme cela a déjà été enseigné, remplace l\'air et l\'eau de la position d\'arrivée à la position de départ du lanceur de sort. Le succès de ce sort et son utilisation très répandue ne sont basés que sur son élégance : le véritable objectif du sort est de remplacer le corps du lanceur de sort par ce qui se trouve devant lui. Le fait que le mage soit déplacé dans la zone lui faisant face n\'est qu\'un effet secondaire.' WHERE `entry` = 3462;
UPDATE `locales_page_text` SET `Text_loc2` = 'Ce sort est suffisamment élégant pour repérer et éviter les personnes la plupart du temps. Les immenses ressources du Kirin Tor sont actuellement utilisées pour perfectionner un sort quasiment parfait, toutefois, n\'oubliez pas que se transférer sur d\'autres personnes volontairement peut provoquer l\'un des trois résultats suivants : le lanceur de sort remplace la cible, la cible remplace le lanceur de sort... ou ils occupent tous deux le même espace, créant de ce fait une abomination dont le Fléau ne voudrait même pas dans ses rangs. Si vous souhaitez éviter ces tragédies, faites attention à votre zone de transfert. Ce qui nous amène...' WHERE `entry` = 3463;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 2 : toujours regarder où vous allez ! Après un nombre incalculable d\'incidents dus à la violation de la règle n° 1, le Kirin Tor a décidé de déplacer cette règle du n° 8 au n° 2. Nous comprenons qu\'un accident puisse se produire, mais certains ne peuvent être aisément réparés. N\'oubliez jamais, amis mages, de regarder des deux côtés de la voie astrale avant de traverser !' WHERE `entry` = 3464;
UPDATE `locales_page_text` SET `Text_loc2` = 'Règle n° 3 : ne jamais se transférer dans un lieu hors de vue. C\'est une précision de la règle n° 2, qui mérite une mention spéciale, car c\'est celle qui est le plus souvent transgressée intentionnellement. De même que pour la règle n° 2, nous avons vu le nombre de rapports de mages rencontrant une fin tragique à cause de leur transfert augmenter considérablement. Certains mages ont admis avoir essayé sciemment de se transférer à travers un mur, dans des zones sombres et même dans des caisses, dans l\'espoir d\'échapper à un poursuivant. Nous souhaitons souligner la stupidité d\'un tel acte.' WHERE `entry` = 3465;
UPDATE `locales_page_text` SET `Text_loc2` = 'Les éléments solides sont accrochés à eux-mêmes si... solidement, qu\'ils en sont... solides. Contrairement à l\'air ou à l\'eau, qui sont facilement dissociables et échangeables, les liens des éléments solides se transfèrent dans le lanceur de sort. Le Kirin Tor se voit obligé de faire la liste de tous les cas de demande d\'indemnisations pour petit désastre en rapport avec des transferts dans des objets solides. Mémorisez ces demandes d\'indemnisations, et évitez de faire ces mêmes erreurs :' WHERE `entry` = 3466;
UPDATE `locales_page_text` SET `Text_loc2` = '10012-c : Retrait par le feu d\'un tabouret de bar coincé dans la hanche de Pétardin Cassebestan. Brûlures collatérales minimes.\n\n19798-g : Retrait de trois (3) tringles de soutien en mithril de la tête de Jénus Killian avec une solution de bière acide. Merci au RAS pour le don de la bière sus-citée. Effets secondaires : perte permanente des cheveux dans la zone affectée.\n\n14761-aa : Retrait de Cynthia Paflemur de la façade d\'une grange au moyen d\'un déchiqueteur gobelin. Dommages collatéraux graves. Heureusement, madame Paflemur peut toujours profiter de la vie avec une main et un pied.' WHERE `entry` = 3467;
UPDATE `locales_page_text` SET `Text_loc2` = '16616-x : Retrait de Harland Wilson de la statue du général Turalyon par le magma, expédié de Forgefer. Dégâts collatéraux modérés. M. Wilson n\'a pas été blessé, mais des élèves à proximité ont été témoins de la fonte du général pour sa récupération, et furent, en conséquence, balafrés à vie.\n\n11773-c : Retrait de six (6) pastèques claquevigne du torse de Sinella Rougelame. Dégâts collatéraux minimes. Quatre (4) pastèques récupérées et données à l\'orphelinat local. \n\n<Cela continue ainsi sur des centaines de pages>' WHERE `entry` = 3468;
UPDATE `locales_page_text` SET `Text_loc2` = 'Je vous prie de ne pas mal prendre les informations que je vous apporte sur la situation, mais nous ne verrons plus l\'apprenti Argoly parmi nous. L\'archimage Ataeric a entraîné ses étudiants dans l\'urgence et m\'a envoyé des cornichons et des benêts qui arrivent à peine à invoquer leurs propres boissons ! J\'attends de ces rigolos qu\'ils accomplissent les devoirs de magi compétents, et ce jeune homme n\'a même pas été capable de faire une simple course.' WHERE `entry` = 3473;
UPDATE `locales_page_text` SET `Text_loc2` = 'L\'herbe d\'Alterac est épaisse et apporte un fort arôme d\'humus au thé chaud. J\'ai envoyé le garçon chercher de l\'herbe fraîche dans les environs de la cité flottante. Je n\'avais pas remarqué qu\'il n\'était jamais revenu, car j\'étais trop occupé à corriger un autre apprenti empoté qui avait mis le feu à une tapisserie de plus de 200 ans.' WHERE `entry` = 3474;
UPDATE `locales_page_text` SET `Text_loc2` = 'Cela m\'a étonné qu\'Argoly sourie comme un idiot lorsque je lui ai confié cette tâche, mais je l\'ai envoyé faire son travail. J\'ai eu la réponse à mes interrogations ce matin, lorsque j\'ai envoyé ma domestique chercher une note importante que j\'avais laissée s\'envoler pendant que j\'admirais les terres gelées sous nos pieds. Elle est revenue précipitamment m\'informer que le corps désarticulé d\'Argoly avait été retrouvé dans la toundra.' WHERE `entry` = 3475;
UPDATE `locales_page_text` SET `Text_loc2` = 'Il ne fit pour moi aucun doute que le garçon était responsable de sa propre fin quand j\'ai retrouvé une bourse de gangrelette dans sa robe. Il semblerait qu\'Argoly ait pris mon ordre de prendre de l\'herbe au pied de la lettre et se soit mis à la mâchonner avant de se mettre au travail. Vous devinerez aisément la suite.' WHERE `entry` = 3476;
UPDATE `locales_page_text` SET `Text_loc2` = 'Thule Serres-de-corbeau\n\nLes informations dont nous disposons sont contradictoires, mais les événements qui se sont déroulés dans les clairières de Tirisfal et la forêt des Pins argentés semblent indiquer que Thule Serres-de-corbeau s’est volontairement associé au Fléau. Il serait peut-être possible de trouver des indices dans les ruines du donjon de Fenris, sur l’une des îles du lac Lordamere, mais pour l’instant, nous devons concentrer notre attention sur d’autres problèmes.' WHERE `entry` = 3479;
UPDATE `locales_page_text` SET `Text_loc2` = 'Gunther Arcanus\n\nProbablement tué au cours de la Troisième guerre. Passé au Fléau.\n\nGunther est toujours en possession de ma pipe préférée. Si quelqu’un découvre ses restes, j’aimerais beaucoup la récupérer.' WHERE `entry` = 3480;
UPDATE `locales_page_text` SET `Text_loc2` = 'Bethor Glacéclat\n\nVictime de la Troisième guerre, Bethor est désormais un Réprouvé, et doit être traité exactement comme tous les agents de la Horde.' WHERE `entry` = 3481;
UPDATE `locales_page_text` SET `Text_loc2` = 'Rheanna,\n\nLe croissant de lune décroît et je ne peux contenir mon impatience à l\'idée de la nouvelle lune, son noir d\'encre s\'étendant sur le ciel nocturne pour cacher nos plaisirs immoraux.\n\nJe manque de souffle, je manque d\'air, j\'aspire à respirer l\'air qui vous entoure.' WHERE `entry` = 3483;
UPDATE `locales_page_text` SET `Text_loc2` = 'Rheanna,\n\nLe temps de la veille est venu, et l\'air froid et nocturne est mon seul compagnon. Les branches robustes montent la garde, impassibles, sur le bosquet où nous avons tenu le conseil. Leurs doigts osseux me giflent, me reprochant mon idiotie, tandis que je fouille les feuillages à votre recherche.\n\nVotre absence m\'est douloureuse, comme seule l\'absence de la femme qui est sienne peut être douloureuse pour un homme.' WHERE `entry` = 3484;
UPDATE `locales_page_text` SET `Text_loc2` = 'Rheanna,\n\nImaginez ma surprise lorsque le postier a refusé de prendre ma lettre pour vous ! Cela ne peut être qu\'une erreur ! Mes yeux parcourent les copies méticuleuses de mes précédentes lettres, mais je ne peux trouver de cause à votre inquiétude fugitive. Je vous livrerai cette lettre en main propre si cet idiot est convaincu que mon amour refuse mes courriers !' WHERE `entry` = 3485;
UPDATE `locales_page_text` SET `Text_loc2` = 'Cher monsieur,\n\nDame Rheanna a demandé explicitement qu\'aucune communication venant de vous ne lui soit transmise, quelles que soient les circonstances. Par la présente, je vous ordonne de vous abstenir de la contacter.\n\nMadame vous informe également que l\'incident de votre métamorphose déplacée, bien que fascinant, n\'est pas une expérience qu\'elle souhaite revivre.' WHERE `entry` = 3486;
UPDATE `locales_page_text` SET `Text_loc2` = 'Q : J\'ai jeté un coup d\'œil au grimoire d\'un copain, dans les vestiaires, et il connaît beaucoup plus de sorts que moi ! Qu\'est-ce qui cloche chez moi ?\n\nR : Tout d\'abord, c\'est tout à fait NORMAL. Parlez régulièrement à votre maître de classe. Il pourra vous apprendre régulièrement de nouveaux sorts. S\'il ne peut rien vous enseigner, c\'est que vous devez vous entraîner à utiliser les sorts que vous connaissez déjà. Soyez patient, vous connaîtrez bientôt tous les sorts nécessaires !' WHERE `entry` = 3504;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée n° 42 - L\'excavation de lignes telluriques continue, avec des résultats satisfaisants. Nous avons été surpris par la similitude qui existe entre les structures telluriques d\'Azeroth et de Draenor, indiquant peut-être une origine similaire ?\nMon proche associé, Naberius, m\'a informé que le clan du Crâne ricanant a conclu une trêve avec l\'Alliance dans la zone. Toujours méfiant vis à vis des orcs, j\'ai pensé « cela peut laisser présager le meilleur, comme le pire ».' WHERE `entry` = 3507;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée n° 205 - Une grande partie des forces de l\'Alliance est retournée sur Azeroth. Avec un peu de chance, les rapports dressés avec soin que nous avons confiés au général Turalyon arriveront à Dalaran en toute sécurité.\nLes portails que Ner\'zhul a imprudemment créés ont provoqué des déchirures dans Farahlon. Les vertes collines s\'écroulent rapidement, à mesure que le Néant distordu corrompt la terre. Il faut que je trouve un moyen de rentrer !' WHERE `entry` = 3508;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée n° 1363 - An 14, Kirin\'Var tient toujours debout. Nous nous réunissons tous les jours pour un repas invoqué par Luminrath, et la magelame inflexible de Dathric a réussi à protéger le village des intrus jusqu\'ici. La destruction de Draenor a presque été une bénédiction car les événements magiques qui ont suivi se sont révélés bien plus intéressants que nous ne l\'aurions imaginé.' WHERE `entry` = 3509;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée n° 1969 - \n<Cette page a été gribouillée dans la précipitation, ce qui crée un contraste saisissant avec les entrées précédentes à l\'écriture soignée.>\n\nNous avons été attaqués... armée de Kael\'thas... par milliers !!\nDes bateaux flottants... bien plus grands que tous les zeppelins qu\'il m\'ait été donné de voir... une magie puissante et étrangère... et une sorte de bombe de mana ?\nJ\'ai lancé un sort de protection sur la tour... aucun signe des autres...\n\n<L\'écriture s\'interrompt.>' WHERE `entry` = 3510;
UPDATE `locales_page_text` SET `Text_loc2` = 'Entrée n° 1970 - Les troupes de Kael\'thas nous ont pris par surprise et m\'ont enfermé dans la tour de Kirin\'Var. Un golem arcanique garde l\'entrée, programmé pour être agressif. Je peux étudier tous les livres que je veux, mais je ne pourrai jamais partir !\nBien que la magie de Kael m\'empêche de communiquer avec mon apprenti, je sens que Ravandwyr est toujours vivant.' WHERE `entry` = 3511;
UPDATE `locales_page_text` SET `Text_loc2` = 'Gnomes – Les gnomes sont de remarquables arcanistes. Ils ont toujours participé au Kirin Tor et, si l\'on compte au poids, ils présentent l’une des plus importantes concentrations de magie du monde.\n\nElfes de la nuit – Les elfes de la nuit ont tendance à éviter l’énergie arcanique à peu près autant que le Fléau, mais leurs pouvoirs druidiques sont sans égal.' WHERE `entry` = 3514;
UPDATE `locales_page_text` SET `Text_loc2` = 'Archimage Antonidas, grand magus du Kirin Tor\n\nLa grande ville de Dalaran se dresse à nouveau, comme un testament à la ténacité et la volonté de son plus grand fils.\n\nVos sacrifices n\'auront pas été vains, mon cher ami.\n\n\nAvec tout mon amour et mon honneur,\n\nJaina Portvaillant' WHERE `entry` = 3542;
UPDATE `locales_page_text` SET `Text_loc2` = '<On dirait qu\'Archavon tenait un journal. Il semble écrit dans différentes langues. Un compte a été tenu sur la couverture.>\n\nHorde :   \n  Donjon défendu : $4024w\n  Donjon capturé : $4022w\n\nAlliance :\n  Donjon défendu : $4025w\n  Donjon capturé : $4023w\n\nJour 10\n\nLes Faiseurs sont partis. Ils m\'ont laissé seul pour surveiller.\n                -ARCHAVON' WHERE `entry` = 3547;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 10500 :\nLes salles sont silencieuses. Vides.\n\nMoi pense les Faiseurs veulent que moi garde la salle, mais ils ont pas vraiment dit « Archavon, garde la salle... » Peut-être c\'est bon si moi garde dehors aussi ? C\'est peut-être moins ennuyeux dehors. C\'est décidé - Moi maintenant responsable de la garde de la salle ET du dehors. Moi prends nouvelles responsabilités le mois prochain.\n                -ARCHAVON\n\nJour 20120 :\nLe dehors est bien plus ouvert que la salle. Il y a des falaises et des montagnes tout près. Moi maintenant sûr que les Faiseurs voulaient que moi garde ça aussi. Moi espère qu\'ils ne se rendront pas compte que seulement été dans la salle pendant la première décennie.\n                -ARCHAVON' WHERE `entry` = 3548;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 1051213 :\nMoi invente un nouveau jeu aujourd\'hui aussi, il s\'appelle « Balance le revenant ». Ai joué du bord du donjon jusqu\'à la route principale aujourd\'hui. Avant l\'an prochain, moi vais essayer de le faire atterrir dans la rivière.\n                -ARCHAVON\n\nJour 2145617 :\nDes petits hommes verts sont venus aujourd\'hui. Moi les ai ajoutés à responsabilités de garde.\n                -ARCHAVON\n\nJour 2145657 :\nLes petits hommes verts ont construits des bâtiments supplémentaires ici maintenant. Plus de bâtiments c\'est bien. Moi crois que parle eux cette semaine et remercie eux.\n                -ARCHAVON\n\nJour 214566 :\nMoi remercie aujourd\'hui un petit homme vert pour les bâtiments en plus. Il dit moi il amène plus de gens à garder pour moi bientôt - des tas.\n\nSuis impatient d\'avoir plus de choses à garder.\n                -ARCHAVON\n"' WHERE `entry` = 3549;
UPDATE `locales_page_text` SET `Text_loc2` = 'Docteur Kohler,$B$BLe chevalier noir n\'a pas encore accompli son destin. Récupérez son cadavre dans l\'enceinte du tournoi et utilisez votre art pour lui rendre la vie. Nous utiliserons la force des croisés et de leurs disciples contre eux.$B$BPrenez des prisonniers et utilisez leur âme pour rendre mon serviteur plus fort. Capturez le croisé Kul, surnommé le Téméraire par ses pairs, et sacrifiez-le sur votre autel. Son esprit imprègnera le chevalier noir d\'une force et d\'un pouvoir incroyables. Puis, envoyez-moi le chevalier noir.' WHERE `entry` = 3569;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 214586 :\nLes petits hommes verts en ont amené plein d\'autres, se sont montrés du doigt, et puis ils se sont tous mis à se battre !\n\nJe reprends responsabilités de garde dans la salle pour sécurité, mais moi emporte des tas de babioles à eux avec moi pour que moi s\'ennuie moins cette fois.\n                -ARCHAVON\n\nJour 214620 :\nLes choses sont devenues plus pires. Moi suis pas sûr de ce que veulent les Faiseurs de moi. Moi essaie de rester dans ma salle, mais les méchantes personnes poursuivent moi plusieurs fois par jour. Ils prennent mes babioles.\n                -ARCHAVON' WHERE `entry` = 3602;
UPDATE `locales_page_text` SET `Text_loc2` = 'Jour 214701 :\nFrères de moi sont revenus ! En fait, ils dormaient dans d\'autres salles fermées.\n\nMoi un peu triste qu\'ile me laissent seul pour tout garder, mais moi partage plus brillantes babioles de moi avec eux quand même parce que moi fatigué être seul et attaqué tout le temps.\n                -ARCHAVON\n\nJour 214760 :\nLes méchantes petites personnes ont commencé à attaquer frères de moi, ça triste. Mais ils laissent moi tranquille la plupart du temps maintenant, ça pas triste.\n\nMoi pense ils veulent les babioles brillantes que moi donner.  Moi sentir moi coupable.\n                -ARCHAVON' WHERE `entry` = 3603;
UPDATE `locales_page_text` SET `Text_loc2` = 'Dédié à tous ceux qui sont tombés face au Fléau pendant la guerre dans les terres gelées.' WHERE `entry` = 3605;





