
SET NAMES utf8;
set names latin1;





UPDATE game_event SET description = 'Solstice d\'été : la fete du Feu' WHERE entry = 1;
UPDATE game_event SET description = 'La fête du Voile d\'hiver' WHERE entry = 2;
UPDATE game_event SET description = 'La foire de Sombrelune (Foret de Terrokar)' WHERE entry = 3;
UPDATE game_event SET description = 'La foire de Sombrelune (Elwynn)' WHERE entry = 4;
UPDATE game_event SET description = 'La foire de Sombrelune (Mulgore)' WHERE entry = 5;
UPDATE game_event SET description = 'Le nouvel an' WHERE entry = 6;
UPDATE game_event SET description = 'La fete lunaire' WHERE entry = 7;
UPDATE game_event SET description = 'De l\'amour dans l\'air' WHERE entry = 8;
UPDATE game_event SET description = 'Le jardin des nobles' WHERE entry = 9;
UPDATE game_event SET description = 'La semaine des enfants' WHERE entry = 10;
UPDATE game_event SET description = 'La fete des moissons' WHERE entry = 11;
UPDATE game_event SET description = 'La Sanssaint' WHERE entry = 12;
UPDATE game_event SET description = 'L\'effort de guerre d\'Ahn Qiraj' WHERE entry = 22;
UPDATE game_event SET description = 'L\'invasion du fleau' WHERE entry = 17;
UPDATE game_event SET description = 'Invasions d\'elementaux' WHERE entry = 13;
UPDATE game_event SET description = 'Annonce du concours de pêche de Strangleronce' WHERE entry = 14;
UPDATE game_event SET description = 'Le coffre pirate de Gurubashi' WHERE entry = 16;
UPDATE game_event SET description = 'Concours de pêche de Strangleronce' WHERE entry = 15;
UPDATE game_event SET description = 'L\'appel aux armes : vallée d\'Alterac !' WHERE entry = 18;
UPDATE game_event SET description = 'L\'appel aux armes : goulet des Chanteguerres !' WHERE entry = 19;
UPDATE game_event SET description = 'L\'appel aux armes : bassin d\'Arathi !' WHERE entry = 20;
UPDATE game_event SET description = 'L\'appel aux armes : l\'oeil du cyclone !' WHERE entry = 21;
UPDATE game_event SET description = 'Attaque des loups : Orgrimmar !' WHERE entry = 24;
UPDATE game_event SET description = 'Attaque des loups : Orgrimmar !' WHERE entry = 23;
UPDATE game_event SET description = 'Fête des Brasseurs' WHERE entry = 26;
UPDATE game_event SET description = 'La Légion de la mort attaque Hurlevent (Attaque des morts-vivants)' WHERE entry = 28;
UPDATE game_event SET description = 'Les grunts d\'Orgrimmar se prépare a défendre!' WHERE entry = 25;
UPDATE game_event SET description = 'L70ETC Concert' WHERE entry = 34;
UPDATE game_event SET description = 'L\'antre de la folie, Gri\'lek' WHERE entry = 35;
UPDATE game_event SET description = 'L\'antre de la folie, Hazza\'rah' WHERE entry = 36;
UPDATE game_event SET description = 'L\'antre de la folie, Renataki' WHERE entry = 37;
UPDATE game_event SET description = 'L\'antre de la folie, Wushoolay' WHERE entry = 38;
UPDATE game_event SET description = 'La nuit tombe en Azeroth' WHERE entry = 29;
UPDATE game_event SET description = 'Jour des Pirates' WHERE entry = 32;
UPDATE game_event SET description = 'Jour des mort' WHERE entry = 40;
UPDATE game_event SET description = 'Bienfaits du pelerin' WHERE entry = 41;
UPDATE game_event SET description = 'L\'appel aux armes : l\'ile des Conquerants!' WHERE entry = 42;
UPDATE game_event SET description = 'Attaque sur le Trépas d\'Orgrim ' WHERE entry = 43;
UPDATE game_event SET description = 'Attaque des demons : Thrallmar !' WHERE entry = 44;
UPDATE game_event SET description = 'Concours de pêche Kalu\'ak ouvert!' WHERE entry = 45;
UPDATE game_event SET description = 'L\'appel aux armes : Rivage des Anciens!' WHERE entry = 30;
UPDATE game_event SET description = 'Arena Season 1' WHERE entry = 124;
UPDATE game_event SET description = 'Arena Season 2' WHERE entry = 125;
UPDATE game_event SET description = 'Arena Season 3' WHERE entry = 126;
UPDATE game_event SET description = 'Arena Season 4' WHERE entry = 127;
UPDATE game_event SET description = 'Arena Season 5' WHERE entry = 128;
UPDATE game_event SET description = 'Arena Season 6' WHERE entry = 129;
UPDATE game_event SET description = 'Arena Season 7' WHERE entry = 130;
UPDATE game_event SET description = 'Arena Season 8' WHERE entry = 131;
UPDATE game_event SET description = 'Arena Season 9' WHERE entry = 132;
UPDATE game_event SET description = 'Janvier' WHERE entry = 50;
UPDATE game_event SET description = 'Février' WHERE entry = 51;
UPDATE game_event SET description = 'Mars' WHERE entry = 52;
UPDATE game_event SET description = 'Avril' WHERE entry = 53;
UPDATE game_event SET description = 'Mai' WHERE entry = 54;
UPDATE game_event SET description = 'Juin' WHERE entry = 55;
UPDATE game_event SET description = 'Juillet' WHERE entry = 56;
UPDATE game_event SET description = 'Août' WHERE entry = 57;
UPDATE game_event SET description = 'Septembre' WHERE entry = 58;
UPDATE game_event SET description = 'Octobre' WHERE entry = 59;
UPDATE game_event SET description = 'Novembre' WHERE entry = 60;
UPDATE game_event SET description = 'Décembre' WHERE entry = 61;
UPDATE game_event SET description = 'La chute de Zalazane' WHERE entry = 46;
UPDATE game_event SET description = 'Opération: Gnomeregan' WHERE entry = 47;
UPDATE game_event SET description = 'Pêche (saison hivernale)' WHERE entry = 64;
UPDATE game_event SET description = 'Pêche (saison estivale)' WHERE entry = 65;
UPDATE game_event SET description = 'Pêche (00.00-06.00)' WHERE entry = 66;
UPDATE game_event SET description = 'Pêche (06.00-12.00)' WHERE entry = 67;
UPDATE game_event SET description = 'Pêche (12.00-18.00)' WHERE entry = 68;
UPDATE game_event SET description = 'Pêche (18.00-00.00)' WHERE entry = 69;
UPDATE game_event SET description = 'Twilight\'s Cult & Invasions d\'élementaux' WHERE entry = 48;
UPDATE game_event SET description = 'Chef de Jin\'Alai, Kutube\'sa' WHERE entry = 27;
UPDATE game_event SET description = 'Chef de Jin\'Alai, Gawanil' WHERE entry = 33;
UPDATE game_event SET description = 'Chef de  Jin\'Alai, Chulo' WHERE entry = 39;
UPDATE game_event SET description = 'Voile d\'Hiver: Cadeau' WHERE entry = 49;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - Perry Gatner annonce' WHERE entry = 62;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - Perry Gatner fait la comédie' WHERE entry = 63;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde- L70ETC Concert Announce' WHERE entry = 70;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - L70ETC Concert' WHERE entry = 71;
UPDATE game_event SET description = 'Hurlevent - Pallissades de la prison brisé' WHERE entry = 72;
UPDATE game_event SET description = 'Concours de pêche de Strangrelonce ouvert' WHERE entry = 73;
UPDATE game_event SET description = 'Concours de pêche Kaluak' WHERE entry = 74;
