/* charset utf8 collate utf8_general_ci; */







UPDATE game_event SET description = 'Solstice d\'été : la fete du Feu' WHERE eventEntry = 1;
UPDATE game_event SET description = 'La fête du Voile d\'hiver' WHERE eventEntry = 2;
UPDATE game_event SET description = 'La foire de Sombrelune (Foret de Terrokar)' WHERE eventEntry = 3;
UPDATE game_event SET description = 'La foire de Sombrelune (Elwynn)' WHERE eventEntry = 4;
UPDATE game_event SET description = 'La foire de Sombrelune (Mulgore)' WHERE eventEntry = 5;
UPDATE game_event SET description = 'Le nouvel an' WHERE eventEntry = 6;
UPDATE game_event SET description = 'La fete lunaire' WHERE eventEntry = 7;
UPDATE game_event SET description = 'De l\'amour dans l\'air' WHERE eventEntry = 8;
UPDATE game_event SET description = 'Le jardin des nobles' WHERE eventEntry = 9;
UPDATE game_event SET description = 'La semaine des enfants' WHERE eventEntry = 10;
UPDATE game_event SET description = 'La fete des moissons' WHERE eventEntry = 11;
UPDATE game_event SET description = 'La Sanssaint' WHERE eventEntry = 12;
UPDATE game_event SET description = 'L\'effort de guerre d\'Ahn Qiraj' WHERE eventEntry = 22;
UPDATE game_event SET description = 'L\'invasion du fleau' WHERE eventEntry = 17;
UPDATE game_event SET description = 'Invasions d\'elementaux' WHERE eventEntry = 13;
UPDATE game_event SET description = 'Annonce du concours de pêche de Strangleronce' WHERE eventEntry = 14;
UPDATE game_event SET description = 'Le coffre pirate de Gurubashi' WHERE eventEntry = 16;
UPDATE game_event SET description = 'Concours de pêche de Strangleronce' WHERE eventEntry = 15;
UPDATE game_event SET description = 'L\'appel aux armes : vallée d\'Alterac !' WHERE eventEntry = 18;
UPDATE game_event SET description = 'L\'appel aux armes : goulet des Chanteguerres !' WHERE eventEntry = 19;
UPDATE game_event SET description = 'L\'appel aux armes : bassin d\'Arathi !' WHERE eventEntry = 20;
UPDATE game_event SET description = 'L\'appel aux armes : l\'oeil du cyclone !' WHERE eventEntry = 21;
UPDATE game_event SET description = 'Attaque des loups : Orgrimmar !' WHERE eventEntry = 24;
UPDATE game_event SET description = 'Attaque des loups : Orgrimmar !' WHERE eventEntry = 23;
UPDATE game_event SET description = 'Fête des Brasseurs' WHERE eventEntry = 26;
UPDATE game_event SET description = 'La Légion de la mort attaque Hurlevent (Attaque des morts-vivants)' WHERE eventEntry = 28;
UPDATE game_event SET description = 'Les grunts d\'Orgrimmar se prépare a défendre!' WHERE eventEntry = 25;
UPDATE game_event SET description = 'L70ETC Concert' WHERE eventEntry = 34;
UPDATE game_event SET description = 'L\'antre de la folie, Gri\'lek' WHERE eventEntry = 35;
UPDATE game_event SET description = 'L\'antre de la folie, Hazza\'rah' WHERE eventEntry = 36;
UPDATE game_event SET description = 'L\'antre de la folie, Renataki' WHERE eventEntry = 37;
UPDATE game_event SET description = 'L\'antre de la folie, Wushoolay' WHERE eventEntry = 38;
UPDATE game_event SET description = 'La nuit tombe en Azeroth' WHERE eventEntry = 29;
UPDATE game_event SET description = 'Jour des Pirates' WHERE eventEntry = 32;
UPDATE game_event SET description = 'Jour des mort' WHERE eventEntry = 40;
UPDATE game_event SET description = 'Bienfaits du pelerin' WHERE eventEntry = 41;
UPDATE game_event SET description = 'L\'appel aux armes : l\'ile des Conquerants!' WHERE eventEntry = 42;
UPDATE game_event SET description = 'Attaque sur le Trépas d\'Orgrim ' WHERE eventEntry = 43;
UPDATE game_event SET description = 'Attaque des demons : Thrallmar !' WHERE eventEntry = 44;
UPDATE game_event SET description = 'Concours de pêche Kalu\'ak ouvert!' WHERE eventEntry = 45;
UPDATE game_event SET description = 'L\'appel aux armes : Rivage des Anciens!' WHERE eventEntry = 30;
UPDATE game_event SET description = 'Arena Season 1' WHERE eventEntry = 124;
UPDATE game_event SET description = 'Arena Season 2' WHERE eventEntry = 125;
UPDATE game_event SET description = 'Arena Season 3' WHERE eventEntry = 126;
UPDATE game_event SET description = 'Arena Season 4' WHERE eventEntry = 127;
UPDATE game_event SET description = 'Arena Season 5' WHERE eventEntry = 128;
UPDATE game_event SET description = 'Arena Season 6' WHERE eventEntry = 129;
UPDATE game_event SET description = 'Arena Season 7' WHERE eventEntry = 130;
UPDATE game_event SET description = 'Arena Season 8' WHERE eventEntry = 131;
UPDATE game_event SET description = 'Arena Season 9' WHERE eventEntry = 132;
UPDATE game_event SET description = 'Janvier' WHERE eventEntry = 50;
UPDATE game_event SET description = 'Février' WHERE eventEntry = 51;
UPDATE game_event SET description = 'Mars' WHERE eventEntry = 52;
UPDATE game_event SET description = 'Avril' WHERE eventEntry = 53;
UPDATE game_event SET description = 'Mai' WHERE eventEntry = 54;
UPDATE game_event SET description = 'Juin' WHERE eventEntry = 55;
UPDATE game_event SET description = 'Juillet' WHERE eventEntry = 56;
UPDATE game_event SET description = 'Août' WHERE eventEntry = 57;
UPDATE game_event SET description = 'Septembre' WHERE eventEntry = 58;
UPDATE game_event SET description = 'Octobre' WHERE eventEntry = 59;
UPDATE game_event SET description = 'Novembre' WHERE eventEntry = 60;
UPDATE game_event SET description = 'Décembre' WHERE eventEntry = 61;
UPDATE game_event SET description = 'La chute de Zalazane' WHERE eventEntry = 46;
UPDATE game_event SET description = 'Opération: Gnomeregan' WHERE eventEntry = 47;
UPDATE game_event SET description = 'Pêche (saison hivernale)' WHERE eventEntry = 64;
UPDATE game_event SET description = 'Pêche (saison estivale)' WHERE eventEntry = 65;
UPDATE game_event SET description = 'Pêche (00.00-06.00)' WHERE eventEntry = 66;
UPDATE game_event SET description = 'Pêche (06.00-12.00)' WHERE eventEntry = 67;
UPDATE game_event SET description = 'Pêche (12.00-18.00)' WHERE eventEntry = 68;
UPDATE game_event SET description = 'Pêche (18.00-00.00)' WHERE eventEntry = 69;
UPDATE game_event SET description = 'Twilight\'s Cult & Invasions d\'élementaux' WHERE eventEntry = 48;
UPDATE game_event SET description = 'Chef de Jin\'Alai, Kutube\'sa' WHERE eventEntry = 27;
UPDATE game_event SET description = 'Chef de Jin\'Alai, Gawanil' WHERE eventEntry = 33;
UPDATE game_event SET description = 'Chef de  Jin\'Alai, Chulo' WHERE eventEntry = 39;
UPDATE game_event SET description = 'Voile d\'Hiver: Cadeau' WHERE eventEntry = 49;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - Perry Gatner annonce' WHERE eventEntry = 62;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - Perry Gatner fait la comédie' WHERE eventEntry = 63;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde- L70ETC Concert Announce' WHERE eventEntry = 70;
UPDATE game_event SET description = 'Taverne d\'extrémité du monde - L70ETC Concert' WHERE eventEntry = 71;
UPDATE game_event SET description = 'Hurlevent - Pallissades de la prison brisé' WHERE eventEntry = 72;
UPDATE game_event SET description = 'Concours de pêche de Strangrelonce ouvert' WHERE eventEntry = 73;
UPDATE game_event SET description = 'Concours de pêche Kaluak' WHERE eventEntry = 74;
